### ISSUE TITLE
May it support upload diretory to the app's documents directory?

### ISSUE THREAD

**Issue by dickeylth** [ios-control/ios-deploy#101]
I'm really appreciated for the ability of upload file to the app's directory with the help of `ios-deploy`, which I've searched for long, thank you so much!

But now I need to upload a whole directory to somewhere under the app's directory, is it possible to support upload of directory? Otherwise I have to iterate files and upload them one by one.

Thank you again!

**Comment by gabebear** [comment]
Closing for age
