### ISSUE TITLE
[v2.0] Node.js version (native shared library loaded using node-ffi)

### ISSUE THREAD

**Issue by shazron** [ios-control/ios-deploy#103]
The code will be partitioned into:
1. CLI portion (node.js)
2. Shared library portion (native)

(1) will load and use (2). The CLI portion will use node, and will load (2) using node-ffi.

**Comment by ligaz** [comment]
Hey @shazron,

We have already implemented something similar here: https://github.com/telerik/mobile-cli-lib/blob/master/mobile/ios/ios-device.ts#L317 

Do you think it makes sense to make it a separate npm package so you can reuse it?

**Comment by shazron** [comment]
Hi @ligaz,
Sorry for the late reply. Didn't know about your lib, and the license is attractive (versus ios-deploy which is GPL). 

I would have to study it and see if it offers all the features that is already documented (or maybe perhaps you can tell me if you know: https://github.com/phonegap/ios-deploy/blob/master/README.md). I would definitely use your lib instead for ios-deploy 2.0 if it met all requirements.

**Comment by shazron** [comment]
Update: we could use nbind https://github.com/charto/nbind but then we need to use C++ classes which may not be a good idea

**Comment by shazron** [comment]
Investigate possibly compiling this to WebAssembly. WebAssembly is exposed under the `--expose-wasm` flag in node (probably at least >6)

**Comment by shazron** [comment]
Another alternative: N-API https://hackernoon.com/n-api-and-getting-started-with-writing-c-addons-for-node-js-cf061b3eae75

**Comment by gabebear** [comment]
I'm closing this because it's really old
