### ISSUE TITLE
Feature request: add the ability to detect if the app is already running

### ISSUE THREAD

**Issue by oscahie** [ios-control/ios-deploy#104]
The idea is simple: one could use ios-deploy to keep an app running for a long period, including auto-restarting it after a crash or after being terminated by the OS for whatever reason. Currently I can kinda do this already in a rudimentary way, since relaunching an already launched app (with -L, i.e. no debugging) does not seem to have any ill effects, but it'd be nicer to just be able to query the device for whether the app is still running or not.

**Comment by gabebear** [comment]
I don't think there is going to be a clean way to implement this and I'm unclear about the utility. Please re-open if this is a pressing need.
