### ISSUE TITLE
Stop application

### ISSUE THREAD

**Issue by kkaefer** [ios-control/ios-deploy#117]
It'd be cool to have a separate "stop application" command. The use case would be to call this in a bash script's trap handler to ensure proper app shutdown.

**Comment by hackjustu** [comment]
+1

**Comment by shazron** [comment]
Please test PR #214 for this feature (see instructions in that PR). See Terminal instructions below.

Note the last line will overwrite your currently installed global ios-deploy. To restore it, just do `npm install -g ios-deploy`

```
git clone https://github.com/rLadia/ios-deploy.git ios-deploy-test
cd ios-deploy-test
git checkout stopapp
npm install -g .
```

**Comment by advantiss** [comment]
My testing shows that it is not stopping running app, which was started by previous ios-deploy command. 
Steps to reproduce:
1) Open Terminal window
2) Run application with ios-deploy .... -d
3) Open new Terminal window
4) While process running in first window, run ios-deploy with  --stopapp to terminate app started in first Terminal window
5) Error appears, ios-deploy unable to find running application. (see log)

```
(lldb)     script fruitstrap_device_app="/private/var/mobile/Applications/D9E887F3-311A-4F6F-8843-DCA388489314/MyApp.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:49713"
(lldb)     command script import "/tmp/41A49342-C7FC-4340-A349-850B4D3C8718/fruitstrap_6d82cc61fedb798d7d9aac715ec4cfcc0f26d0cc.py"
(lldb)     command script add -f fruitstrap_6d82cc61fedb798d7d9aac715ec4cfcc0f26d0cc.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_6d82cc61fedb798d7d9aac715ec4cfcc0f26d0cc.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_6d82cc61fedb798d7d9aac715ec4cfcc0f26d0cc.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_6d82cc61fedb798d7d9aac715ec4cfcc0f26d0cc.safequit_command safequit
(lldb)     connect
(lldb)     run
error: process launch failed: timed out trying to launch app
(lldb)     kill
error: Process must be launched.
```

**Comment by hoihoi8** [comment]
+1

**Comment by rLadia** [comment]
Sorry for the delay.

I'm not sure if ios-deploy handles multiple instances very well in general. For example, `ios-deploy --bundle /bundle --debug` followed by `ios-deploy --bundle /bundle --debug` will result in the same error.

A workaround would be to kill any previous ios-deploy instances before running this command.

**Comment by alexander-poulikakos** [comment]
+1 to add this feature

**Comment by fatfatson** [comment]
+1 in 2018.11

**Comment by fatfatson** [comment]
i have slightly modified the source to support the stop function: just add a `-S` option
you could have a try:
https://github.com/fatfatson/ios-deploy

**Comment by gabebear** [comment]
Closing this for same reasons in https://github.com/ios-control/ios-deploy/pull/376
