### ISSUE TITLE
lldb process don't die

### ISSUE THREAD

**Issue by Incont** [ios-control/ios-deploy#146]
I use python:
command = "ios-deploy --id b9cdc896eb3dc093c6a4ed732fb9bf79xxxxxxxx --bundle test.app --noinstall --debug"
process = subprocess.Popen([command], shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
...
process.kill()

lldb and ios-deploy processes don't die

if in my case this is not possible, you please add the output used list PID processes

**Comment by gabebear** [comment]
Closing this for age.

If this is still an issue we can reopen it(more errors on why the process can't be killed would be helpful as well).
