### ISSUE TITLE
List the path of installed application?

### ISSUE THREAD

**Issue by headupinclouds** [ios-control/ios-deploy#150]
The following command:

```
ios-deploy --bundle_id ${BUNDLE_ID} --list
```

Lists the relative path for the applications folders (/Documents/file.png, etc).  

Similarly, the to command references files relative to the application itself:

```
ios-deploy --bundle_id ${BUNDLE_ID} --upload some_file.png -to Documents/some_file.png
```

Is there a way to retrieve the absolute path of the folders (directly or through concatenation of some APP_PATH  + "/Document/file.png"?  I'm running some simple native code directly in main.mm which needs the full path name.

**Comment by headupinclouds** [comment]
This is probably a rare use case, but In case anybody else needs to do this you can use the "HOME" environment variable (who knew?) from inside native code.  

```
std::string home = getenv("HOME");
std::string documentsDir  = home + "/Documents";
```

The absolute path option for ios-deploy would still be a nice feature.

**Comment by gabebear** [comment]
Closing for age (and has workaround)
