### ISSUE TITLE
How to pass environment variable to ios-deploy?

### ISSUE THREAD

**Issue by mobileharness-eng** [ios-control/ios-deploy#173]
I used libimobile/idevicedebug to run the iOS test before.

Because libimobile/idevicedebug can not provide LLDB debug log, I want to switch to use ios-deploy. The problem is I don't know how to pass environment variables to ios-deploy, while I can add "-e" to pass environment variables.

**Comment by palmerc** [comment]
I submitted a PR for this

**Comment by gabebear** [comment]
Fixed in https://github.com/ios-control/ios-deploy/pull/354
