### ISSUE TITLE
Timed out waiting app to launch

### ISSUE THREAD

**Issue by louisatome** [ios-control/ios-deploy#193]
When i try to install and launch my app using the command `./ios-deploy -i deviceID -L -b myAPP.app`, i get the error `error: process launch failed: timed out waiting for app to launch` and the process hangs. I see my app being launched and killed few seconds after the launching.

**Comment by louisatome** [comment]
It seems to be linked somehow with the provisioning profile i use.
If my .app has been built with a Development profile it works but if it has been built with a Production profile i have the above error.

**Comment by shazron** [comment]
1.8.6 published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by louisatome** [comment]
I tried the 1.8.6 release but I still cannot deploy a production app. But the process doesn't hang anymore.
Now, i get the error : 
`error: process launch failed: failed to get the task for process 6303`

Still no problem with the development version of my app.

**Comment by shazron** [comment]
Is this still an issue? I have no problems with deploying a properly signed up with the right provisioning.

**Comment by louisatome** [comment]
Yes I still have the issue. I try to deploy an app which use an Ad Hoc Distribution provisioning profile. I can install it without any problem (with ios-deploy or iTunes) but when ios-deploy try to launch it, i get the above error and the app is killed.

**Comment by shazron** [comment]
I'm not 100% sure but I strongly suspect ios-deploy only works on non-production builds - only works on dev cert signed builds :/

**Comment by Ukalnins** [comment]
This is, stricly speaking, ios-deploy problem. The lldb remote launch command timeouts after some 30 seconds and kills the process automatically, if it did not start in the timeframe. For kdp and gdb plugins, there is a setting in lldb to change this timeout, but for ios these do not seem to work, so I dont think ios-deploy can change anything in this.

The Distribution provisioning profile most probably is used by ios to forbid debugging/messing with the process as a security mesure.

**Comment by gabebear** [comment]
Closing for age, will open a new ticket about checking for get-task-allow entitlement
