### ISSUE TITLE
ios-deploy tries to use "Latest" developer disk image for old iOS versions 

### ISSUE THREAD

**Issue by gennadykr** [ios-control/ios-deploy#221]
I discovered that ios-deploy works only for iOS9.3 after system update.
I noticed that it always uses the "Latest" folder for developer disk image:

> Device support path: /Users/tester/Library/Developer/Xcode/iOS DeviceSupport/8.4.1 (12H321)
> Developer disk image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/Latest/DeveloperDiskImage.dmg

I found a workaround: creating of additional symlinks for the proper folders:

> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
> lrwxr-xr-x  1 root  wheel    3 Apr  6 18:36 8.4.1 (12H321) -> 8.4
> lrwxr-xr-x  1 root  wheel    3 Apr  6 04:33 9.2.1 (13D15) -> 9.2

`ios-deploy -i <UDID> -b <fat binary>.app -I -m -u -L -v`
# Expected behavior

App was launched, ios-deploy exited writing "safequit" and "Process detached"
# Actual behavior.

Error:
2016-04-06 18:32:04.099 ios-deploy[61937:178989] [ !! ] Unable to mount developer disk image. (e8000033)
# Steps to reproduce the problem

Try to run app launch command for an iOS device with version of iOS less then 9.3
`ios-deploy -i <UDID> -b <fat binary>.app -I -m -u -L -v`
You will see the error "Unable to mount developer disk image. (e8000033)".
Add link to the proper developer disk folder for iOS version defined in "Device support path" to get rid of the error.
# System Specs
- [ ] 1. sw_vers -productVersion 10.11.4
- [ ] 2. ios-deploy -V 1.8.5
- [ ] 3. xcodebuild -version Xcode 7.3 Build version 7D175
- [ ] 4. xcode-select --print-path /Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
  Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
  Apple LLVM version 7.3.0 (clang-703.0.29)
  Target: x86_64-apple-darwin15.4.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version lldb-350.0.21.3

**Comment by shazron** [comment]
We had this in the old Makefile that wasn't migrated to Xcode/npm scripts:
https://github.com/phonegap/ios-deploy/blob/6d61b7ca7c0ff16caea4e87a91ee7535db888621/Makefile#L21-L22

**Comment by gennadykr** [comment]
But I installed it as required with npm. Now I have uninstalled and installed it again (see attached npm log), and I have rechecked the the problem persists.
[npm-install-out.txt](https://github.com/phonegap/ios-deploy/files/210602/npm-install-out.txt)

If it turns to be installation problem I will not submit the second issue I observed. The app launches without problem only for 64bit devices, and it freezes after "safequit" before "Process detached" for 32bit ones, even for the same iOS version 9.2.1 for iPod touch 5th and 6th generation.

**Comment by shazron** [comment]
You did nothing wrong, I was pointing out the bug in the installer as you observed.
We have a discussion in #218 and a possible fix in #223

**Comment by shazron** [comment]
For the original issue, the problem with adding the symlink in the npm pre-install script is, the DeviceSupport folder is owned by root (especially if you installed from the Mac App Store), and I don't want a superuser requirement to install ios-deploy.

**Comment by shazron** [comment]
Looking at the code, it will only look at the "Latest" symlink if it exhausts all the other locations: 
https://github.com/phonegap/ios-deploy/blob/3ef9dfefcf8a26e555cf3b0f2eba9585510d4b65/src/ios-deploy/ios-deploy.m#L504-L506 so this "detection" is where its failing, possibly the version and/or buildversion.

This version has been working with iOS 8.x, so I don't think it's specifically that.

**Comment by shazron** [comment]
Temporary workaround:
```
cd `xcode-select --print-path`/Platforms/iPhoneOS.platform/DeviceSupport 
ln -sfn "`find . -type d -maxdepth 1 -exec basename {} \; | tail -1`" Latest
cd -
```

For the second line, you might need to `sudo`.

**Comment by gennadykr** [comment]
Functions copy_device_support_path and copy_developer_disk_image_path look very similar, but directory they seek for has different naming.
Device support path folder "Library/Developer/Xcode/iOS DeviceSupport" has only folders with build in parenthesis, like "8.4.1 (12H321)".
But Developer disk image folder "iPhoneOS.platform/DeviceSupport" has in name usually short part of version like "8.4" instead of "8.4.1".
That is each build has its own symbols but for a minor version developer disk image is the same as for a major version.
It looks like for some iOS version or for some XCode version algorithm fails to find "Developer disk image" folder (#73).
Can it be because of AMDeviceCopyValue returns different values for "ProductVersion" in different XCode versions?
It looks like in this case copy_device_support_path will not work, and symlink workaround also will not work.
Or can it be that CFStringCreateArrayBySeparatingStrings works wrong with dividing string on parts? Believe that no.
Suppose that the algorithm can find full version and cannot find its part. 
That is for iOS version "8.4.1" it can find folder with "8.4.1" in its name, but cannot find folder with more short name "8.4".
And it seems that I found why it behaves so: when in the while loop on version parts it should decrease number of parts
`CFArrayRemoveValueAtIndex(version_parts, CFArrayGetCount(version_parts) - 1);`
it always has non-zero path with the "Latest" folder and so it does break from the loop.
Because of this it can find 8.4.1 but it cannot check the shorter variant.
It seems like it must seek for "Latest" after the while loop ends and only if the path is empty.

But I have the working for iOS 8.1.3 configuration with ios-deploy 1.8.3.
And I do not understand how it can work.
> Device support path: /Users/tester/Library/Developer/Xcode/iOS DeviceSupport/8.1.3 (12B466)
> Developer disk image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/8.1/DeveloperDiskImage.dmg
>10.10.5
1.8.3
Xcode 7.2.1
Build version 7C1002
/Applications/Xcode.app/Contents/Developer
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
lldb-340.4.119.1

Uff. I understood. There are no "Latest" in the folder on the machine (may be somebody removed it?):
>bash-3.2$ ls -l
total 0
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 6.0
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 6.1
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 7.0
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 7.1
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 8.0
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 8.1
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 8.2
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 8.3
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 8.4
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 9.0
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 9.1
drwxr-xr-x  4 root  wheel  136 Feb  3 18:49 9.2 (13C75)
bash-3.2$

So, this is the second workaround to let the current code work correctly: remove "Latest" link from the developer disk image folder
>/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

(For the first machine configuration I reported the issue, this folder contains "Latest" folder)

**Comment by gennadykr** [comment]
Please, consider adding the attached patch to fix the problem (changes for copy_developer_disk_image_path only)
[patch.txt](https://github.com/phonegap/ios-deploy/files/215072/patch.txt)

**Comment by shazron** [comment]
Thanks @gennadykr for all the info and the patch.
As you can see the code we inherited is in one monolithic file -- the functions you mentioned are prime candidates for the first unit tests for this utility. Will try to get this done a.s.a.p to isolate the failing test before or after applying the fix.

**Comment by 1N50MN14** [comment]
Having the same problem here after upgrading to XCode 8, reinstalled from npm latest, didn't help.

**Comment by paulshapiro** [comment]
Appear to be having this problem as well. Device has 10.2 but latest on computer is 10.3. 

Strangely, sym-linking Latest to 10.2 still showed the same failure ("Unable to mount…"). 

Restarted device as well, no joy.

Please advise! 

Best,
Paul

**Comment by yipcma** [comment]
face same issue here with Unable to mount developer disk image

**Comment by shazron** [comment]
@yipcma try the latest version 1.9.2

**Comment by yipcma** [comment]
same thing....

**Comment by gabebear** [comment]
Closing for age
