### ISSUE TITLE
Can we just start the debugserver (skip the install phase)?

### ISSUE THREAD

**Issue by tobefuturer** [ios-control/ios-deploy#225]
If I have installed my application, can we skip the install phase and start the debugserver ?

**Comment by akofman** [comment]
Hello @tobefuturer, what about the `--noinstall` flag ?

**Comment by tobefuturer** [comment]
Thanks , it works. I overlook this flag;

ios-deploy -m -n -b demo.app

I find that the application launched very slowly after enter 'run' to lldb, but in xcode fast.
Is there some other setting flag I ignore ?

**Comment by akofman** [comment]
Your welcome. I saw other issues about this slowness, you don't have a special flag for that but are you using the last version (1.8.6) ?

**Comment by tobefuturer** [comment]
yes, my ios-deploy version is 1.8.6 , and I also try the newest code (version 2.0.0) on github .

**Comment by tobefuturer** [comment]
I find  ```lldb.target.Launch(lldb.SBLaunchInfo......)``` (in run_command in lldb.py file)  spend so much time, but I don't know how to optimize. :-(

**Comment by gabebear** [comment]
closing for age
