### ISSUE TITLE
autoexit exits prematurely when debugger stops

### ISSUE THREAD

**Issue by gusc** [ios-control/ios-deploy#231]
I was having an issue that sometimes (and by that I mean at random and a lot) ios-deploy exits with a status code 254 and there is an error message "error: invalid thread". So I did some digging and found out that, when this error occurs, the event loop in lldb.py autoexit_command function receives a state set to lldb.eStateStopped (a.k.a. debugger has stopped).

The problem here is that there is still some output coming form the app which get's truncated right after this error as the lldb exits and so does ios-deploy. Now if I remove the exit call in this block my app continues to run, I can get the rest of the output and it will continue to run till it reaches a proper exit state event (eStateExited).

So my question/issue is - shouldn't the autoexit call for an exit when the app exits not when the debugger stops debugging?

I did the testing with ios-deploy 1.8.6 and 2.0.0 on OS X El Capitan.

Edit: fixed typos (iso->ios) :)

**Comment by gabebear** [comment]
Closing for age
