### ISSUE TITLE
Merge issue with running command line args

### ISSUE THREAD

**Issue by ptc-dberry** [ios-control/ios-deploy#259]
ios-deploy --noninteractive --debug --noinstall --bundle_id com.foo.myapp --bundle myapp.app --args "-p myarg"
# Expected behavior

The application runs and uses the command line argument
# Actual behavior.

The running of the application fails to use the command line argument

I believe the issue is this in lldb.py there was a merge commit baa524eda5b0d106b71a897bc3b12c34abb1196d which removed a change that was added in commit feb51d582a075a47c1ca0df82762044bc9c634d0

I believe the commented out line below should be as it was from the second commit above.

```
if len(args) > 1:
    args_arr = shlex.split(args[1] and args[1] or '{args}')
    # args_arr = shlex.split(args[1])
else:
    args_arr = shlex.split('{args}')
lldb.target.Launch(lldb.SBLaunchInfo(args_arr), error)
```
# Steps to reproduce the problem

See above for the proposed fix
# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.
- [ ] 1. sw_vers -productVersion
  10.11.6
- [ ] 2. ios-deploy -V
  2.0.0
- [ ] 3. xcodebuild -version
  Xcode 7.2
  Build version 7C68
- [ ] 4. xcode-select --print-path
  /Applications/Xcode_72.app/Contents/Developer
- [ ] 5. gcc --version
  Apple LLVM version 7.0.2 (clang-700.1.81)
  Target: x86_64-apple-darwin15.6.0
  Thread model: posix
- [ ] 6. lldb --version
  lldb-340.4.119

**Comment by dot-asm** [comment]
In other words it appears that in reporter's case args[1] somehow ends up defined but empty. It ought be specific to Xcode version, as last modification was verified to work with Xcode 8.0. Either way, it appears to be appropriate to adjust the code. Earlier a concern was expressed that `(args[1] and args[1] or '{args}')` has limited readability. Alternative the context of this report can be:
```
if len(args) > 1 and args[1]:
    args_arr = shlex.split(args[1])
else:
    args_arr = shlex.split('{args}')
```
Can you confirm this working?

**Comment by ptc-dberry** [comment]
Sorry for the late reply I'm just taking a look at our usage in detail again. At the moment I suspect I was mistaken with the errors I was seeing being related to this. As our usage actually goes down the else branch of the code. I'll confirm shortly.

**Comment by shazron** [comment]
@ptc-dberry any word?

**Comment by shazron** [comment]
Slated to relook at this for 1.9.2

**Comment by ptc-dberry** [comment]
Sorry yes the original change was fine, my mistake.

**Comment by pMaske** [comment]
Has this been fixed?
I am still seeing command line arguments are being ignored when calling ios-deploy

**Comment by simoncat42** [comment]
Any progress on this? I don't understand what the format is for the arguments option, either. I've tried:

`  ios-deploy --debug --envs DYLD_PRINT_STATISTICS=1 --args hello=1 --bundle /Users/chomsky/Desktop/FE22.2.8-apple.app
    ios-deploy --debug --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args hello 1 --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "FOO=BAR BAZ=FAZ" --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "-p myarg" --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "-p FOO=BAR" --bundle /Users/chomsky/Desktop/webtest.app
`

None of them seem to work!

**Comment by simoncat42** [comment]
@gabebear Thanks for the hint, but I'm pretty far from knowing anything about ObjC. I'm just a lowly user! I had a look and it seems like it's related to that `{args}` biz, but I don't know much more than that.

**Comment by ivanhernandez13** [comment]
Missed this yesterday, I'll see if I have a chance to look into this today or tomorrow.

**Comment by simoncat42** [comment]
@ivanhernandez13 Thanks, man! So excited to get it working.

**Comment by ivanhernandez13** [comment]
Hmm could this be a version issue? Pulled and built from head to try this out and it appears to work as expected or am I missing something?

```
$ ~/Build/Products/Debug/ios-deploy --bundle ~/Desktop/ArgPrinter.app --debug --args "--HELLO_WORD=1 -p FOO=BAR hello 1"
[...]
(lldb)     connect
(lldb)     run
success
ProcessInfo.processInfo.arguments[0]: /var/containers/Bundle/Application/6F050078-DE56-4533-A959-FC33F8DF5B46/ArgPrinter.app/ArgPrinter
ProcessInfo.processInfo.arguments[1]: --HELLO_WORD=1
ProcessInfo.processInfo.arguments[2]: -p
ProcessInfo.processInfo.arguments[3]: FOO=BAR
ProcessInfo.processInfo.arguments[4]: hello
ProcessInfo.processInfo.arguments[5]: 1
```

**Comment by gabebear** [comment]
Closing this since I don't believe it is still an issue

**Comment by RMRMesquita** [comment]
I still have this issue
`ios-deploy --debug --envs DYLD_PRINT_STATISTICS=1  --bundle /Users/ruimesquita/Developer/myapp.app`
This does not show any information regarding the pre-main statistics.
Using the version 1.11.0
iPad with iOS 13.6

**Comment by gabebear** [comment]
@RMRMesquita Just verifying that you do see the output when using Xcode?

**Comment by RMRMesquita** [comment]
Using the Xcode it outputs the pre-main information. I output the flags from the lunchInfo object and the correct env vars are there.
When using a device with iOS 12 it works as expected.

**Comment by gabebear** [comment]
I'm betting this is really something weird with DYLD_PRINT_STATISTICS rather than `envs` not getting passed... Would need to dig in and see what all extra variables are set by Xcode that aren't getting sent when you are running with ios-deploy.  https://stackoverflow.com/questions/33776715/dyld-print-statistics-not-showing-anything

**Comment by RMRMesquita** [comment]
Made it work, just added the `DYLD_LIBRARY_PATH=/usr/lib/system/introspection` to the env vars  😄

**Comment by RMRMesquita** [comment]
I've managed to make it work. I added this envs `CA_ASSERT_MAIN_THREAD_TRANSACTIONS=0 OS_ACTIVITY_DT_MODE=1 DYLD_PRINT_STATISTICS=1 DYLD_PRINT_TO_STDERR=1 CA_DEBUG_TRANSACTIONS=0 __LLVM_PROFILE_RT_INIT_ONCE=__LLVM_PROFILE_RT_INIT_ONCE SQLITE_ENABLE_THREAD_ASSERTIONS=1 DYLD_LIBRARY_PATH=/usr/lib/system/introspection` to ios-deploy and the pre-main statistics are now being shown.
Thanks for the tip @gabebear, hope this can help you.

**Comment by kikaxa** [comment]
> Closing this since I don't believe it is still an issue

Unless there were fixes https://github.com/ios-control/ios-deploy/issues/395 is likely to still be broken.

**Comment by ChaseTargaryen** [comment]
I don't believe this is fixed.

ios-deploy --justlaunch --bundle bundleName --args hello world = 1

ios-deploy --justlaunch --bundle bundleName --args "hello world = 1"

ios-deploy --justlaunch --bundle bundleName --args {"hello world = 1"}

ios-deploy --debug --justlaunch --bundle bundleName --args hello world = 1

ios-deploy --debug --justlaunch --bundle bundleName --args "hello world = 1"

ios-deploy --debug --justlaunch --bundle bundleName --args {"hello world = 1"}

NONE of them work

**Comment by gabebear** [comment]
@ChaseTargaryen Generally you don't put spaces in variable names, what are you trying to set with the following?
>   --args hello world = 1

**Comment by ivanhernandez13** [comment]
@ChaseTargaryen Can you print out the contents of `CommandLine.arguments` in your app to ensure they are not getting passed. [Swift docs for CommandLine.arguments](https://developer.apple.com/documentation/swift/commandline/2294816-arguments)

Might also want to check the version of ios-deploy you're using (`ios-deploy --version`), latest build is 1.11.3.

**Comment by ChaseTargaryen** [comment]
I'm on the latest build.
I'm using Solar2d and I didn't get any launch arguments from ios-deploy.
The arguments is empty. The xcode console isn't showing any anything so I really don't have anything to show you.

**Comment by pMaske** [comment]
@ChaseTargaryen Try passing like this...I have been using following in my test framework and it works great.

ios-deploy --args "-AutoRun true -BuildNum $BUILD_NUM"

**Comment by ccxla** [comment]
> ios-deploy --args "-AutoRun true -BuildNum $BUILD_NUM"

does not work for me, but

`ios-deploy --args "-app-arg:-AutoRun -app-arg:true -app-arg:-BuildNum -app-arg:$BUILD_NUM"`

does (see https://stackoverflow.com/a/9525233).

**Comment by ajschwieterman** [comment]
Surround the arguments with single quotes.  That works for me.

`ios-deploy --args '-AutoRun true -BuildNum $BUILD_NUM'`
