### ISSUE TITLE
Create gem official mirror

### ISSUE THREAD

**Issue by orkenstein** [ios-control/ios-deploy#271]
Please, create official `gem` for `ios-deploy`. As iOS developer we usually use `gem` + `bundler`.
There's one repo, but it looks abandoned:
https://www.google.no/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwinppjhnd3QAhUE3SwKHVzjDycQFggcMAA&url=https%3A%2F%2Fgithub.com%2Fmokagio%2Fios-deploy-gem&usg=AFQjCNFd3GrhB3rna0ol0gPqQkttPCYGwA

**Comment by shazron** [comment]
To be honest, I'm not interested in this but will leave this open in case someone else wants to send a pull request, etc.

**Comment by gabebear** [comment]
closing for age
