### ISSUE TITLE
--justlaunch option doesn't work as expected with distribution credentials

### ISSUE THREAD

**Issue by grmorcl** [ios-control/ios-deploy#275]
# Expected behavior

Invoking ios-deploy -L -b <path_to_ipa_file> on an ipa file that has been signed using distribution credentials should deploy the app to the device, launch the app and quit.  The app should remain running on the device.

# Actual behavior

Invoking ios-deploy -L -b <path_to_ipa_file> on an ipa file that has been signed using distribution credentials causes the ipa file to be deployed to the device and the app launched, but the debugger (lldb) tries to attach to the running app and can't, which leads to an error being reported and the app hangs at the splashscreen for a few seconds, then crashes.

# Steps to reproduce the problem

1. Create a simple iOS app (e.g. using cordova create)
2. Build and sign the app using distribution (not developer) credentials (e.g. using cordova build --buildConfig buildConfig.json)
3. Invoke ios-deploy -L -b <path_to_ipa_file>

# System Specs

Mac OS X 10.11.6.  Xcode 8.2.  iPhone 6 running iOS 10.2.

- [x] 1. sw_vers -productVersion 
10.11.6
- [x] 2. ios-deploy -V 
1.9.0
- [x] 3. xcodebuild -version 
Xcode 8.2 
Build version 8C38
- [x] 4. xcode-select --print-path 
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version
lldb-360.1.70

**Comment by grmorcl** [comment]
Hi, any update on this, pls?

**Comment by blakdragan7** [comment]
Would love to get this working as well

**Comment by grmorcl** [comment]
Just wondering what the plan is here?  Should we expect this in 1.9.3 or 2.0.0?

**Comment by surajpindoria** [comment]
I will take a look into this. Most likely will end up in 1.9.3.

**Comment by grmorcl** [comment]
Thanks!

**Comment by grmorcl** [comment]
Hi, could you provide an update on progress pls?

**Comment by gabebear** [comment]
I don't think this is an issue anymore,

Closing for age; please re-open if this is still an issue.

**Comment by karankalsi** [comment]
@gabebear Facing a similar issue, Any way via which we can skip lldb on `Distribution` Signed builds?

**Comment by gabebear** [comment]
The only way ios-deploy can launch an app on a phone is via lldb; I'm not sure it is possible to use the lldb debugger to launch an non-debuggable binary.

There are three major kinds of "Distribution" credentials:
1. AdHoc - very similar to Developer but with debugging disabled
2. Enterprise - Need a special AppStoreConnect account to generate these but these can install on any device without being registered first. Debugging is disabled.
3. AppStore - impossible to run locally; only for uploading to Apple.

I'm guessing you are wanting to launch an non-debuggable Adhoc signed IPA on the phone using the debugger. I probably wouldn't have time to look into this myself, but you can re-open this bug if or open a new bug and reference this old bug if you want this use case looked into further. We do accept patches if you want to work on it.

**Comment by borrrden** [comment]
I've had similar reservations regarding this.  It seems there is no way to run an app without starting a debug server, which I don't really want to do.  I know it's possible to do so because other products (like xharness) have done it and I believe that you can do this now with devicectl.  Is that functionality just not present in the underlying library in pre-devicectl Xcodes?
