### ISSUE TITLE
Feature request: ability to dump program output to stdout

### ISSUE THREAD

**Issue by DoDoENT** [ios-control/ios-deploy#276]
Hi!

I am not using PhoneGap/Cordova for app development, however I use iso-deploy script from CMake/CTest to deploy my GoogleTest-based c++ unit tests to iPhone connected to CI server. The procedure is as follows:

1. First generate Xcode project with CMake using [iOS toolchain](https://github.com/microblink/build/blob/master/toolchains/ios.toolchain.cmake).
2. Build all targets with `cmake --build .`
3. Run `ctest`.

I've configured `ctest` to launch tests with `ios-deploy` with following command:

    add_test( NAME ${_TEST_NAME} COMMAND ${IOS_DEPLOY} --bundle ${CMAKE_BINARY_DIR}/Release-iphoneos/${exeName}.app --justlaunch --args --gtest_filter=${testname} ${ARGUMENTS} )

This works flawlessly, except that `ctest` is unable to capture program output (written with functions like `NSLog`, `printf` or with streaming to `std::cout`) - those outputs are perfectly visible inside Xcode console (_Target Output_ window).

Is there a possibility to add flag to `ios-deploy` which will allow dumping of program output to `stdout`? In my case I don't need LLDB debugging, so a flag which would not start lldb would also be useful, but not necessary.

**Comment by gabebear** [comment]
Closing for age, please re-open if this is still an issue.

There are now `--nolldb` and `--output` options
