### ISSUE TITLE
"Error 0xe8008016: The executable was signed with invalid entitlements."

### ISSUE THREAD

**Issue by tslug** [ios-control/ios-deploy#281]
I'm getting this error when I try to use ios-deploy to install an app on an iPad 3:

2017-02-06 19:17:43.391 ios-deploy[46408:1772945] [ !! ] Error 0xe8008016: The executable was signed with invalid entitlements. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

I realize this is probably nothing to do with ios-deploy itself, but because most people seem to use XCode, it's extremely difficult to find people knowledgeable about what the embedded.mobileprovision file should look like and whether the entitlements are valid.  I thought I'd post on here and see if you could offer suggestions on how to isolate how the entitlements differ and why.

These are the command line arguments I use to install the 
ios-deploy --debug --bundle /tmp/Payload/app_name.app

The file seems to transfer fine, and the expected behaviour is for the app to install and run on my iPad 3.

Actual behavior is that error message after the transfer.  It doesn't install or run after that.

This is an Adobe AIR 24 application, so the app descriptor file contains a section for entitlements that looks like this:

        <Entitlements><![CDATA[
            <key>application-identifier</key>
            <string>MU9BA6CJS5.com.wf.boon</string>
            <key>aps-environment</key>
            <string>production</string>
            <key>get-task-allow</key>
            <true />
            <key>com.apple.developer.game-center</key>
            <true />
            <key>com.apple.developer.in-app-payments</key>
            <true />
            <key>beta-reports-active</key>
            <true />
            <key>keychain-access-groups</key>
            <array>
                <string>MU9BA6CJS5.*</string>
            </array>]]>
        </Entitlements>

The get-task-allow, game-center, and in-app-payments keys are things I'm trying to see if I can get it to work.  It used to work when none of those were added.  The get-task-allow key will end up in the embedded.mobileprovision file, but the other two won't, probably because I have the wrong syntax for them.

Running ios-deploy on a 2010 17" MacBook Pro with OSX 10.10.5 (Yosemite).  Connected to an iPad 3.

- [ ] 1. system_profiler SPSoftwareDataType

Software:

    System Software Overview:

      System Version: OS X 10.10.5 (14F1713)
      Kernel Version: Darwin 14.5.0
      Boot Volume: ssdhd1
      Boot Mode: Normal
      Computer Name: ddtmbp
      User Name: Dave Taylor (davetaylor)
      Secure Virtual Memory: Enabled
      Time since boot: 8 days 2:06

- [ ] 2. ios-deploy -V

1.9.1

- [ ] 3. xcodebuild -version

Xcode 7.2
Build version 7C68

(Not aware that I'm using Xcode at all, btw, all Adobe AIR toolchain)

- [ ] 4. xcode-select --print-path

/Applications/Xcode.app/Contents/Developer

(Not aware that I'm using Xcode at all, btw, all Adobe AIR toolchain)

- [ ] 5. gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

(Note that I'm using Adobe AIR's mxmlc to compile)

- [ ] 6. lldb --version

lldb-340.4.119

(Note that I'm using Adobe AIR's adt to link/sign/package)

**Comment by shazron** [comment]
You could always create a dummy iOS project and edit the Capabilities, to see what Xcode writes to the .entitlements file as a reference. Xcode -> Project Icon in Project Navigator -> Target -> Capabilities

**Comment by gabebear** [comment]
Closing this for age
