### ISSUE TITLE
Error 0xe8000051

### ISSUE THREAD

**Issue by yangshengtao** [ios-control/ios-deploy#282]
when run ios-deploy, I met this's error:
ios-deploy[5700:108532] [ !! ] Error 0xe8000051: Could not inspect the application package. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by shazron** [comment]
When you selected "New Issue", you chose to delete the template contents. Please enter the required information for a bug report.

**Comment by gabebear** [comment]
Closing for age
