### ISSUE TITLE
Feature request: Storing device_db in the separate human-editable file

### ISSUE THREAD

**Issue by black-square** [ios-control/ios-deploy#284]
I think it would be more convenient if `device_db` array is stored in the separate text file and everyone could modify it locally without a need to update the binary. We can completely get rid of hardcoded `device_db` in the code or have a text file as an addition to the hardcoded array. In the second case, text file should be able to overwrite the hardcoded data.

**Comment by shazron** [comment]
Good idea. How do we make this as convenient as possible for users? Do we look for a dotfile in their home directory? I doubt most would want to dive into editing a file where the binary is.

**Comment by black-square** [comment]
@shazron Sorry for delayed response. I made some experiments and now I think ios-deploy doesn't need to provide `device_db` functionality at all. It should retrieve more device-specific data and let the user find human-readable names or we can create a simple BASH script as a separate project to do that.

Personally, I'll be perfectly enough for me having names like `iPhone7,2` instead of `N61AP` and we can get this name without any table. 

E.g. if you run 
```
mobiledevice list_device_props | xargs -t -L1 mobiledevice get_device_prop
```
using https://github.com/imkira/mobiledevice it will print many interesting properties, like:
```
mobiledevice get_device_prop CPUArchitecture
arm64

mobiledevice get_device_prop DeviceClass
iPhone

mobiledevice get_device_prop DeviceName
iPhone

mobiledevice get_device_prop HardwareModel
N61AP

mobiledevice get_device_prop HardwarePlatform
t7000

mobiledevice get_device_prop ModelNumber
MG472

mobiledevice get_device_prop ProductType
iPhone7,2

mobiledevice get_device_prop ProductVersion
10.2.1

mobiledevice get_device_prop SerialNumber
**************
```
etc.

I believe we can use all these keys in `AMDeviceCopyValue`, return the result to the user in the format which is friendly for parsing and forget about the rest.

What do you think?

**Comment by shazron** [comment]
This is great stuff. I really hate maintaining a db and would rather use a programmatic way.

**Comment by gabebear** [comment]
imkira/mobiledevice seems to have been abandoned.
