### ISSUE TITLE
Understanding error exit codes from ios-deploy

### ISSUE THREAD

**Issue by hackjutsu** [ios-control/ios-deploy#287]
We encountered the error exit code 253 in different situations, some for disk image error, some for provisioning profile issue.

It looks like this [file](https://github.com/phonegap/ios-deploy/blob/ed7c70aa593bec97dcd7bf71ab25fbabf724ce70/src/errors.h) has some clues on error codes interpretation, but I don't know how they are mapped to the exit codes.

It would be helpful if we have these exit codes documented somewhere.  If this documentation already exists, please just let me know.

Thanks:)

**Comment by gabebear** [comment]
Closing for age... but exit code 257 is a very generic code.
