### ISSUE TITLE
App exists but cannot download

### ISSUE THREAD

**Issue by emptygalaxy** [ios-control/ios-deploy#309]
# Expected behavior
My iPhone is connected and recognized by ios-deploy. When I check if an app is installed is says it is but whenever I am trying to download files from that app it says app cannot be found. Is there a way to enable listing/downloading files?

$ ios-deploy --bundle_id "com.dji.go" -e
[....] Waiting for iOS device to be connected
[....] Using 701a48d2************059ab (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'Nick's iPhone'.
true

$ ios-deploy --bundle_id "com.dji.go" --list
[....] Waiting for iOS device to be connected
[....] Using 701a48d2************059ab (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'Nick's iPhone'.
2017-08-13 22:33:47.794 ios-deploy[95067:12279442] [ !! ] Unable to find bundle with id: com.dji.go

# System Specs
- [ System Version: macOS 10.12.6 (16G29), Kernel Version: Darwin 16.7.0 ] 1. system_profiler SPSoftwareDataType
- [ 1.9.1 ] 2. ios-deploy -V
- [ Xcode 8.3.3, Build version 8E3004b ] 3. xcodebuild -version
- [ /Applications/Xcode.app/Contents/Developer ] 4. xcode-select --print-path
- [ Apple LLVM version 8.1.0 (clang-802.0.42) ] 5. gcc --version
- [ lldb-370.0.42, Swift-3.1 ] 6. lldb --version

**Comment by nguyenhoangmisfit** [comment]
It seems that ios-deploy does not work with iOS 11.

**Comment by surajpindoria** [comment]
@nguyenhoangmisfit What version of ios-deploy are you using?

**Comment by nguyenhoangmisfit** [comment]
@surajpindoria it's 1.9.1

**Comment by surajpindoria** [comment]
Can you try with the latest version, 1.9.2.

**Comment by emptygalaxy** [comment]
@surajpindoria It still happens in 1.9.2.

$ ios-deploy -V
1.9.2
$ ios-deploy -1 com.dji.go -e
[....] Waiting for iOS device to be connected
[....] Using 51942.....32fese (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'Nick's iPhone'.
true
$ ios-deploy -1 com.dji.go -l
[....] Waiting for iOS device to be connected
[....] Using 51942.....32fese (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'Nick's iPhone'.
2017-10-15 22:04:10.989 ios-deploy[18675:1035636] [ !! ] Unable to find bundle with id: com.dji.go

**Comment by shazron** [comment]
It's possible iOS 11 has tightened up things. Can you confirm that the same ios-deploy version lists your files under iOS 10?

**Comment by lavi-xu** [comment]
I tried on 10.3.3. It reports same error:
2017-12-05 00:45:32.776 ios-deploy[37580:2653874] [ !! ] Unable to find bundle with id: com.netgear.insightstaging

**Comment by lavi-xu** [comment]
Tried with latest version from git, same error:
$ ./build/Release/ios-deploy -V
2.0.0
$ ./build/Release/ios-deploy -1 com.netgear.insightstaging -l
[....] Waiting for iOS device to be connected
[....] Using xxx (J71tAP, iPad (2017), iphoneos, arm64) a.k.a. '“Administrator”的 iPad'.
2017-12-05 01:11:51.585 ios-deploy[37663:2656917] [ !! ] Unable to find bundle with id: com.netgear.insightstaging

**Comment by emptygalaxy** [comment]
I just tried it again with the latest version (2.0.0), still the same result. "Unable to find bundle with id".
Tried it on three different iPhone's and an iPad.

**Comment by gabebear** [comment]
Closing for age
