### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by adudurant** [ios-control/ios-deploy#310]
I have  an app  (test.app) .I could install it in real device with command  "ios-deploy -b test.app".Then I zip test.app into test.zip and could not be installed in  real device .What 's more  I  installed test.zip yesterday  successfully.
The error as follows, 
2017-08-23 18:23:21.024 ios-deploy[173:6692859] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by shazron** [comment]
You can only deploy using a `.app` not `.zip`. ios-deploy does not do any unzipping and just does a straight install.

**Comment by adudurant** [comment]
@shazron  Thanks！ But ，when I try to deploy a  .app。 The command returns an error while the app successfully installed。

**Comment by shazron** [comment]
Is this issue still relevant? I answered your question initially since you tried to install a .zip and it gave an error, and I said we don't support installing .zips.
