### ISSUE TITLE
ios-deploy only works as expected for non-sudo user who installed it

### ISSUE THREAD

**Issue by mikelupo** [ios-control/ios-deploy#318]
Include the **command line arguments** you used for ios-deploy.
ios-deploy -V  (other commands except -h behave the same)

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

# Expected behavior
Should work for all users on the mac

# Actual behavior.
no error, but no output.
Only works for the user who installed it. userA.
userB gets no output from ios-deploy -V (or other commands except -h)
elevating to sudo 'sudo ios-deploy -V' gives 2.0.0

# Steps to reproduce the problem
ran the npm install with the options for OSX el'capitan and greater. (I'm on Sierra)
then run a few ios-deploy commands. 
-h works as any user. -V outputs nothing as does other commands that do work.

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType
System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: bos-mp8dq
      Boot Mode: Normal
      Computer Name: bos-mp8dq
      User Name: XXXXXX
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 17:14
- [ ] 2. ios-deploy -V
blank without sudo. WIth sudo 2.0.0

- [ ] 3. Xcode 9.0
Build version 9A235

- [ ] 4. xcode-select --print-path
/Applications/Xcode9.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode9.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-900.0.45
  Swift-4.0

**Comment by shazron** [comment]
This could be classified as a bug or feature request -- I'm treating this as a feature request

**Comment by gabebear** [comment]
Closing since npm is not the recommended way to install ios-deploy anymore. Please use homebrew.
