### ISSUE TITLE
Cannot deploy when iOS device is connected through the network

### ISSUE THREAD

**Issue by shazron** [ios-control/ios-deploy#320]
Xcode 9 introduces WiFi debugging. Enable first when tethered in `Xcode -> Window -> Devices and Simulators`. For your device, check the "Connect via network" checkbox.

`ios-deploy -c` doesn't show the device.

<img width="1042" alt="xcode - window - devices and simulators" src="https://user-images.githubusercontent.com/36107/32258961-6e2b98e6-bef8-11e7-8b1a-4271713a4b3b.png">

# Expected behavior

Able to deploy using WiFi.

# Actual behavior.

Cannot deploy using WiFi.

# Steps to reproduce the problem

1. Enable WiFi connection to device using Xcode 9 (see description above)
2. Deploy normally

# System Specs

Xcode 9.1
iOS 11.1
macOS Sierra 12.6
ios-deploy 1.9.2

**Comment by francescodoffizi** [comment]
Same here, no way to list the device nor deploy via network connection.

**Comment by juliodutra2003** [comment]
Same problem here. But, i already deploy through network before. Today stop listing my device as an option in xcode.
A

**Comment by llamafilm** [comment]
I see there is an option `-W, --no-wifi` so is this feature supposed to be implemented?  I can't see my device over wifi.

**Comment by gabebear** [comment]
I believe this is fixed
