### ISSUE TITLE
NodeJS in server

### ISSUE THREAD

**Issue by hhkkxx** [ios-control/ios-deploy#323]
Hello,

I am developing a website in RecatiJs, so I need to install NodeJs on the server (kimsufi hoster).

I installed NodeJs by following this link: https://www.a2hosting.com/uk/kb/installable-applications/manual-installations/installing-node-js-on-managed-hosting-accounts

All is good there, when I mark grace = puTTY in SSH after communicating to the server (node ​​- version), it sorts the node version well, so it is installed.

I managed to launch but I have a problem, it must concern rights:

Once I enter my folder and start npm it will show me the error message:

`blabla@0.1.0 start /home/blabla/web
> react-scripts start
 
sh: /home/blabla/web/node_modules/.bin/react-scripts: Permission non accordée
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! blabla@0.1.0 start: `react-scripts start`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the blabla@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/blabla/.npm/_logs/2018-01-04T15_38_58_596Z-debug.log`

Je précise que je suis en SSH et que je me connecte au server à l'aide de puTTY...

Je poursuis mes recherches !

**Comment by shazron** [comment]
I'm not sure I see an ios-deploy issue here in your log. Is this an ios-deploy issue?
