### ISSUE TITLE
Cannot deploy iOS app on iOS >= 11 - Error 0x800801c: AMDeviceSecureInstallApplication

### ISSUE THREAD

**Issue by g4b0** [ios-control/ios-deploy#328]
# Expected behavior
Running a debug version with framework7 (cordova) works fine on iPad mini v. 9.3.5. 
Command launched:
$ f7 run ios --device

# Actual behavior.
The same command fail on iPad v. 11.0.3 with the following error:

```
2018-02-14 10:14:13.043 ios-deploy[1706:19554] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/g4b0/Documents/TestApp/platforms/ios/build/device/Test.app
```

Building the ipa for release works fine, and it install also on devices with iOS >= 11 through plist file

# Steps to reproduce the problem
Just run a debug cordova/framework7 app on a device with version >= 11

# System Specs

- [x] 1. system_profiler SPSoftwareDataType
- [x] 2. ios-deploy -V
- [x] 3. xcodebuild -version
- [x] 4. xcode-select --print-path
- [x] 5. gcc --version
- [x] 6. lldb --version

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
      Boot Volume: SSD HD
      Boot Mode: Normal
      Computer Name: Mac mini 
      User Name: g4b0 (g4b0)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 1:02
$ ios-deploy -V
1.9.2
$ xcodebuild -version
Xcode 9.2
Build version 9C40b
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ lldb --version
lldb-900.0.64
  Swift-4.0
```

I found this old closed, but resolved similar issue: https://github.com/phonegap/ios-deploy/issues/148

**Comment by lingtingSir** [comment]
+1

**Comment by shazron** [comment]
AMDeviceSecureInstallApplication is usually 100% because the .app was not signed properly (as other bugs filed here can attest). ios-deploy is "dumb" -- it will try to install your app without caring if its signed or not, and will throw this error if not signed.

**Comment by shazron** [comment]
Closing since this is not an ios-deploy problem, but likely a Cordova configuration problem
