### ISSUE TITLE
Running an already installed app

### ISSUE THREAD

**Issue by jgoldring** [ios-control/ios-deploy#329]
I am trying to find a way to launch an app that is already installed on a physical IPhone to cut down on automation time installing the app. Right now it seems like the --noinstall flag should allow for a command like:

ios-deploy --noinstall --noninteractive --bundle_id <install-app-bundle>

whereby the installed app is ran. Instead, you are forced to provide the --bundle arg, which I am assuming translates into using the .app path to copy the files across, run the app, and then delete all the files thus fulfilling the --noinstall part.

Is it possible to use ios-deploy to run an app that is already installed to the device, or is there a specific reason a bundle has to be specified?

**Comment by v73alice** [comment]
i want to know that too

**Comment by iprox** [comment]
I got the same question,
so right now there is no way to run the app without installation, is that right?

**Comment by gabebear** [comment]
This should be possible with the `--noinstall` option.

**Comment by saratchandrakarumuri** [comment]
@gabebear But why do we need to pass bundle again to launch a previously installed app. Why can't we launch the app just by using the bundle id?
