### ISSUE TITLE
Error ios-deploy: The service is invalid. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)

### ISSUE THREAD

**Issue by Juliocbr** [ios-control/ios-deploy#336]
Hi,

this error appears when I use "ionic cordova run ios -l -c --device --address xx.xx.xx"
......
------ Debug phase ------
Starting debug of 4ac15d8ddaa048b7d54b126cd2d529cd852ce062 (N51AP, iPhone 5s (GSM), iphoneos, arm64) a.k.a. 'iPhone de Desarrollo' connected through USB...
[  0%] Looking up developer disk image
[ 90%] Mounting developer disk image
[ 95%] Developer disk image already mounted
**2018-04-26 16:25:28.407 ios-deploy[7547:407838] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/name/Documentos/ionic/mobile-app/platforms/ios/build/device/app_name.app**

[ERROR] An error occurred while running cordova run ios --device (exit code 1).
 
ionic info:
ios-deploy        : 1.9.2 
ios-sim           : 6.1.2 
Xcode             : Xcode 9.2 Build version 9C40b 
ionic (Ionic CLI) : 3.20.0

iphone iOS version 11.3.1
Thanks

**Comment by Juliocbr** [comment]
Probably I need to update my xcode to 9.3 version.

**Comment by pharazone** [comment]
the same problem

**Comment by Juliocbr** [comment]
@pharazone you need to update your xcode o the latest version (9.3.1).
In my case this problem was solved by updating xcode.

**Comment by pharazone** [comment]
@Juliocbr  You're right, after updating my Xcode,it worked with no problem.
