### ISSUE TITLE
Can't download files from Wifi-connected devices

### ISSUE THREAD

**Issue by ChrisMash** [ios-control/ios-deploy#340]
Trying to download files from devices (iPad/AppleTV) connected over wifi (rather than usb) silently fails. Works fine if they're connected over usb (bear in mind that the 4k AppleTV can't be connected over USB).

Run command:
ios-deploy -i <device_id> --bundle_id <bundle_id> --download=/Library --to dl

# Expected behavior
The contents of the /Library folder are downloaded to the 'dl' folder

# Actual behavior.
Nothing is downloaded, no errors are output

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
System Version: macOS 10.13.4 (17E199)
      Kernel Version: Darwin 17.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Chris' MacBook Pro
      User Name: Chris Mash (chrismash)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 6:16
- [x] 2. ios-deploy -V
1.9.2
- [x] 3. xcodebuild -version
Xcode 9.3
Build version 9E145
- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version
lldb-902.0.79.2
Swift-4.1

**Comment by dstimm-gpfw** [comment]
I am also having the same problem.

**Comment by gabebear** [comment]
This should work now
