### ISSUE TITLE
Launch command stucks after multiple relaunches

### ISSUE THREAD

**Issue by rawatsunil92** [ios-control/ios-deploy#341]
I have a test app which crash, as there are bugs, but I am re-launching if it crashes. Consecutive launches works fine but after multiple relaunch ios-deploy command just hangs. Used ios-deploy command:- iOS-deploy --id <deviceid> --noninteractive --noinstall --no-wifi --bundle ios.app --args -rerun
--noninteractive options helps me to identify when app is finished or crashed so that I can retry again. But at this stage it is hanged and app isn't launched hence it is stuck waiting forever.
I tried "killall iOS-deploy" and "killall lldb". It kills current execution of ios-deploy command but subsequent ios-deploy launch command (since I am launching again and again until finished) stuck again.
I can use ios-deploy --list command from seperate terminal. But ios-deploy --rm command is also failing:
 iOS-deploy --id <deviceid> --rm='/Documents/test_output/Log.txt' --bundle_id <bundleid>
[....] Waiting for iOS device to be connected
[....] Using (J99aAP, iPad Pro (12.9"), iphoneos, arm64) a.k.a. 'iPad (4)'.
Assertion failed: (AFCRemovePath(afc_conn_p, target_filename) == 0), function remove_path, file /Users/kathait/.npm-global/lib/node_modules/ios-deploy/src/ios-deploy/ios-deploy.m, line 1452.
Abort trap: 6

Received below error when killed all ios-deploy from different terminal:
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode-9.2.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined

This requires me to kill the terminal/python script which is running in loop and start again.

**Expected Behaviour** - ios-deploy launch command should not stuck.

**Steps to Reproduce** - run ios-deploy app launch in continous loop.

**System Software Overview:**

      System Version: macOS 10.13.2 (17C88)
      Kernel Version: Darwin 17.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5:06
ios-deploy -V
1.9.2
xcodebuild -version
Xcode 9.2
Build version 9C40b
xcode-select --print-path
/Applications/Xcode-9.2.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode-9.2.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode-9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
lldb --version
lldb-900.0.64
  Swift-4.0

**Comment by rawatsunil92** [comment]
Below error was received when default python version was changed to 2.7.15 as another package installation made it default. Setting python 2.7.10 as default resolves this issue but ios-deploy do stuck intermittently
STDERR: Traceback (most recent call last):
File "", line 1, in 
File "/Applications/Xcode-9.2.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/init.py", line 98, in 
import six
ImportError: No module named six

**Comment by nikolayev** [comment]
+1

**Comment by deedora** [comment]
+1

**Comment by gabebear** [comment]
Closing for age... I also wonder if this was happening because of a busted Xcode version because ios-deploy's Python doesn't include `six`
