### ISSUE TITLE
Can it deploy and run cordova app which was built with --release?

### ISSUE THREAD

**Issue by qiluo** [ios-control/ios-deploy#345]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.
# Expected behavior
I'm building an Ionic/cordova app. I can properly deploy and launch my app in debug mode, the build script was 
```
ionic cordova run ios --prod --device --debug
```
I would expect it also work for release version

# Actual behavior.
Once I changed build with `--release` option,
The build script was 
```
ionic cordova run ios --prod --device --release
```
I always got following error

```
lldb)     command script add -f fruitstrap_e5fa85267ccace8dd36d59e3dd25e21660bc7ba4.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_e5fa85267ccace8dd36d59e3dd25e21660bc7ba4.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_e5fa85267ccace8dd36d59e3dd25e21660bc7ba4.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_e5fa85267ccace8dd36d59e3dd25e21660bc7ba4.safequit_command safequit
(lldb)     connect
(lldb)     run
error: process launch failed: failed to get the task for process 841
(lldb)     safequit

Application has not been launched

(node:52456) UnhandledPromiseRejectionWarning: Error code 1 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/dev/ionic-apps/my-app/platforms/ios/build/device/demo.app
(node:52456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Steps to reproduce the problem

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
- [ ] 2. ios-deploy -V   `1.9.2`
- [ ] 3. xcodebuild -version  `Xcode 9.2 Build version 9C40b`
- [ ] 4. xcode-select --print-path   `/Applications/Xcode.app/Contents/Developer`
- [ ] 5. gcc --version   `Apple LLVM version 9.0.0 (clang-900.0.39.2)`
- [ ] 6. lldb --version   `lldb-900.0.64`

```
System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ABC
      User Name: ABC
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by shazron** [comment]
This is not a Cordova issue tracker. Closing.
