### ISSUE TITLE
ios-deploy throws error if you have it as dependency in package.json on Windows

### ISSUE THREAD

**Issue by nerdic-coder** [ios-control/ios-deploy#355]
# Expected behavior
ios-deploy should be skipped on windows when detected in a projects package.json dependencies or devDependecies, like this:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.3 (node_modules\ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

# Actual behavior.
The `npm install` throws the following error and stop the installation of the projects other dependencies:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for ios-deploy@1.9.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

# Steps to reproduce the problem
Add "ios-deploy": "1.9.3" to a package.json devDependencies and run 'npm install' on a windows machine.

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
```
system_profiler SPSoftwareDataType
'system_profiler' is not recognized as an internal or external command,
operable program or batch file.
```

- [x] 2. ios-deploy -V
```
'ios-deploy' is not recognized as an internal or external command,
operable program or batch file.
```

- [x] 3. xcodebuild -version
```
'xcodebuild' is not recognized as an internal or external command,
operable program or batch file.
```

- [x] 4. xcode-select --print-path
```
'xcode-select' is not recognized as an internal or external command,
operable program or batch file.
```

- [x] 5. gcc --version
```
'gcc' is not recognized as an internal or external command,
operable program or batch file.
```

- [x] 6. lldb --version
```
'lldb' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by nerdic-coder** [comment]
Found a solution for this.
I just needed to add ios-deploy as an optionalDependency and it is skipped with a warning.
I'm closing this issue.

Example from package.json in my project:
`"optionalDependencies": {
    "ios-deploy": "1.9.3"
  }`

**Comment by nitea27** [comment]
thanks
