### ISSUE TITLE
Command Script Import Error

### ISSUE THREAD

**Issue by collindutter** [ios-control/ios-deploy#361]
# Expected behavior
Application is successfully deployed to device.

# Actual behavior.
This error is thrown.
`(lldb)     command script import "/tmp/3EB6F875-710A-4E62-A4A0-7782DFFB29A7/fruitstrap_00008020-001654991178002E.py"
error: module importing failed: ('invalid syntax', ('temp.py', 1, 27, 'import fruitstrap_00008020-001654991178002E\n'))
backtrace unavailable`

# Steps to reproduce the problem
Run:
`ios-deploy --justlaunch --no-wifi -d -b my.app`

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [X] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14 (18A391)
      Kernel Version: Darwin 18.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Collin’s MacBook Pro
      User Name: Collin Dutter (collindutter)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3:00
- [X] 2. ios-deploy -V
2.0.0
- [X] 3. xcodebuild -version
Xcode 10.0
Build version 10A255
- [X] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [X] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [X] 6. lldb --version
lldb-1000.11.37.1
  Swift-4.2

**Comment by collindutter** [comment]
So after lots of poking around it seems like the issue stems from the device id being found containing a hyphen which is an illegal character for a python module...

**Comment by joshstrange** [comment]
Look like this line here would need to be changed to "clean" the hyphen https://github.com/ios-control/ios-deploy/blob/fccb5954c37d8c947564dee2a90be1642db00697/src/ios-deploy/ios-deploy.m#L689

**Comment by collindutter** [comment]
Yeah this PR addresses the issue https://github.com/ios-control/ios-deploy/pull/360
