### ISSUE TITLE
Impossible to run with Xcode 10's and Cordova 

### ISSUE THREAD

**Issue by brankoenero** [ios-control/ios-deploy#364]
# Expected behavior
Run app_name.app into device automatically.

# Actual behavior.
The application is copied and installed into the device but an error happens when try to launch.

# Steps to reproduce the problem
- Install xCode Version 10.0 (10A255)
- Create Cordova project and build successfully.
- Install ios-deploy 1.9.4
- Run command line: ios-deploy --justlaunch --debug --bundle app_name.app --verbose

# System Specs
- [ ] 1. system_profiler SPSoftwareDataType
``` 
System Version: macOS 10.13.6 (17G2307)
Kernel Version: Darwin 17.7.0
Boot Volume: Macintosh HD
Boot Mode: Normal
Computer Name: XXXXXXXXXX
User Name: XXXXXXXXXX
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
Time since boot: 9:48
```
- [ ] 2. ios-deploy -V
```
1.9.4
```
- [ ] 3. xcodebuild -version
```
Xcode 10.0
Build version 10A25
```
- [ ] 4. xcode-select --print-path
```
/Applications/Xcode.app/Contents/Developer
```
- [ ] 5. gcc --version
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [ ] 6. lldb --version
```
lldb-1000.11.37.1
Swift-4.2
```

# Message Error
It is shows splash screen but then it crash.
After copied, installed, connected to remote debug server:
```
(lldb) command source -s 0 '/tmp/345C5B77-B536-4CA0-8801-9B784FB90F15/fruitstrap-lldb-prep-cmds-5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465'
Executing commands in '/tmp/345C5B77-B536-4CA0-8801-9B784FB90F15/fruitstrap-lldb-prep-cmds-5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465'.
(lldb)     platform select remote-ios --sysroot '/Users/username/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/username/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols"
(lldb)     target create "/Users/username/wk_sourcecode/repos/a3d_app_ionic3/platforms/ios/build/device/app_name.app"
Current executable set to '/Users/username/wk_sourcecode/repos/a3d_app_ionic3/platforms/ios/build/device/app_name.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/ABE16684-2843-42C6-90B6-E9F565841077/app_name.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:50863"
(lldb)     target modules search-paths add /usr "/Users/username/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols/usr" /System "/Users/username/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols/System" "/private/var/containers/Bundle/Application/ABE16684-2843-42C6-90B6-E9F565841077" "/Users/username/wk_sourcecode/repos/a3d_app_ionic3/platforms/ios/build/device" "/var/containers/Bundle/Application/ABE16684-2843-42C6-90B6-E9F565841077" "/Users/username/wk_sourcecode/repos/a3d_app_ionic3/platforms/ios/build/device" /Developer "/Users/username/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols/Developer"
(lldb)     command script import "/tmp/345C5B77-B536-4CA0-8801-9B784FB90F15/fruitstrap_5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465.py"
(lldb)     command script add -f fruitstrap_5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_5fbfb11bf7f3a02ae5f3ff073eba16626bcb6465.safequit_command safequit
(lldb)     connect
(lldb)     run
error: process launch failed: failed to get the task for process 787
(lldb)     safequit

Application has not been launched

```

**Comment by shazron** [comment]
What is your python version?
`python --version`

**Comment by shazron** [comment]
Note that the app appears to be installed, then the app stalls when launched. Killing the app and running it again shows that it is still stalled. You can only launch the app to completion after a reboot. Thus the app is properly installed, but can't be launched.

**Comment by shazron** [comment]
It's possible there is an lldb bug with Xcode 10: https://github.com/DerekSelander/lldb_fix
However, when i try to test whatever is in the readme, it gives me an error "error: attach failed: cannot attach to process due to System Integrity Protection". I don't think it's a SIP issue but I will test with SIP off.

**Comment by shazron** [comment]
Turned SIP off, still the same error, so it's not a SIP thing.

**Comment by shazron** [comment]
Confirmed that I encountered the same bug as specified here: https://github.com/DerekSelander/lldb_fix so that is the culprit

**Comment by shazron** [comment]
He has a workaround, which is pretty hairy (see same link). To properly fix this, we can only hope for a new lldb patch from the Xcode team

**Comment by shazron** [comment]
The lldb patch does **not** fix this. I can see it being loaded, but it makes no difference, so it must be something else. I'm investigating whether it's a .app issue or something.

**Comment by shazron** [comment]
I just tried something:
1. Deploy the Cordova app to device using Xcode (make sure it is successful)
2. Find the app in Xcode Project Navigator -> Show In Finder
3. Copy this app somewhere

Then do a:
`ios-deploy -d --bundle APP_LOCATION`. The app installs fine. So Cordova is not building this app properly, thus it won't deploy, so it's not an ios-deploy issue.

**Comment by shazron** [comment]
To 'fix' this in cordova, add the flag `--buildFlag='-UseModernBuildSystem=0'` when running or building

**Comment by brankoenero** [comment]
Hi Sharon,

I answer you by parts:

> What is your python version?
> `python --version`
> (just covering some bases)

Python 2.7.10

> Note that the app appears to be installed, then the app stalls when launched. Killing the app and running it again shows that it is still stalled. You can only launch the app to completion after a reboot. Thus the app is properly installed, but can't be launched.

The application is not properly installed, when I try run it, It just shows a white screen and then it crashes.

> The lldb patch does **not** fix this. I can see the patch being loaded, but it makes no difference, so it must be something else. I'm investigating whether it's a .app issue or something.

Your are right, same behaviour. 

> To 'fix' this in cordova, add the flag `--buildFlag='-UseModernBuildSystem=0'` when running or building

I'm trying running:  ios-deploy --justlaunch --debug --bundle app_name.app --verbose --buildFlag='-UseModernBuildSystem=0' but it displays the following message: ios-deploy: unrecognized option `--buildFlag=-UseModernBuildSystem=0'

Is it normal? I'm doing some wrong.

Thanks.

**Comment by shazron** [comment]
Try the flag in Cordova CLI, actually.
