### ISSUE TITLE
Debug Frida instrumented app fails

### ISSUE THREAD

**Issue by ciplipzip** [ios-control/ios-deploy#368]
# Expected behavior
ios-deploy --noinstall --debug --bundle "Payload/${APPNAME}/"
does not correctly work.

# Actual behavior.
[....] Waiting for iOS device to be connected
[....] Using 97bf26875de8fa0d17649a56f9306c9b36a3b5b4 (N61AP, iPhone 6 (GSM), iphoneos, arm64) a.k.a. '...'.
------ Debug phase ------
Starting debug of 97bf26875de8fa0d17649a56f9306c9b36a3b5b4 (N61AP, iPhone 6 (GSM), iphoneos, arm64) a.k.a. '...' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
[100%] Connecting to remote debug server
-------------------------.
(lldb) command source -s 0 '/tmp/79B6E845-3296-4EFD-B9A1-C3A82DB841E9/fruitstrap-lldb-prep-cmds-97bf26875de8fa0d17649a56f9306c9b36a3b5b4'
Executing commands in '/tmp/79B6E845-3296-4EFD-B9A1-C3A82DB841E9/fruitstrap-lldb-prep-cmds-97bf26875de8fa0d17649a56f9306c9b36a3b5b4'.
(lldb)     platform select remote-ios --sysroot '/Users/lucespo2/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/lucespo2/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols"
(lldb)     target create "/Users/lucespo2/Downloads/Fridpa-master/Payload/Tinder.app"
Current executable set to '/Users/lucespo2/Downloads/Fridpa-master/Payload/Tinder.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/690A605E-01E2-4F44-A02A-D27003E44B5F/Tinder.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:51201"
(lldb)     target modules search-paths add /usr "/Users/lucespo2/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols/usr" /System "/Users/lucespo2/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols/System" "/private/var/containers/Bundle/Application/690A605E-01E2-4F44-A02A-D27003E44B5F" "/Users/lucespo2/Downloads/Fridpa-master/Payload" "/var/containers/Bundle/Application/690A605E-01E2-4F44-A02A-D27003E44B5F" "/Users/lucespo2/Downloads/Fridpa-master/Payload" /Developer "/Users/lucespo2/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols/Developer"
(lldb)     command script import "/tmp/79B6E845-3296-4EFD-B9A1-C3A82DB841E9/fruitstrap_97bf26875de8fa0d17649a56f9306c9b36a3b5b4.py"
(lldb)     command script add -f fruitstrap_97bf26875de8fa0d17649a56f9306c9b36a3b5b4.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_97bf26875de8fa0d17649a56f9306c9b36a3b5b4.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_97bf26875de8fa0d17649a56f9306c9b36a3b5b4.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_97bf26875de8fa0d17649a56f9306c9b36a3b5b4.safequit_command safequit
(lldb)     connect
(lldb)     run
error: process launch failed: Unspecified

# Steps to reproduce the problem
- Download Tinder 100.2.1 version for iPhone (NO jailbreak)
- Follow all the steps inside
https://github.com/tanprathan/Fridpa/blob/master/fridpa.sh
- Command
ios-deploy --noinstall --debug --bundle "Payload/${APPNAME}/"
shows the error.

I'm trying to instrument Tinder using Frida with my developer certificate (NOT distribution), but I lead to that error. I have an iPhone 6 (iOS 12.1) attached via USB.
The app opens and immediately crashes!

# System Specs

+ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.1 (18B75)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBook Pro di Lucia 
      User Name: Lu Ces (lucespo2)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:06

+ ios-deploy -V
1.9.4
+ xcodebuild -version
Xcode 10.1
Build version 10B61
+ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
+ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
+ lldb --version
lldb-1000.11.38.2
  Swift-4.2

Thanks to whoever wants to help me: I'm desperate... Struggling for days with that.

**Comment by palmerc** [comment]
Without spending any time on this... did you try this with other apps? Are you sure Tinder doesn't have some form of repackaging detection?

**Comment by Rackles** [comment]
I have the same error but with two apps we developed internally where I'm sure we didn't use any repackaging detection.

Does anyone have other ideas on why it crashes?

**Comment by gabebear** [comment]
I'd like to stay fairly far away from re-packaging random apps... but if you have a valid IPA you should be able to install it through iTunes/Xcode without ios-deploy.

If you tun into issues with a valid IPA that installs manually through iTunes/Xcode, but that won't install via ios-deploy, please re-open.
