### ISSUE TITLE
Ownership of Repo?

### ISSUE THREAD

**Issue by aflofo** [ios-control/ios-deploy#369]
Why does https://github.com/phonegap/ios-deploy redirect here was there an ownership switch. I am very confused. Furthermore does the GPL3 license of the repo make it so that if you use ios-deploy with cordova that you have open source your code.

**Comment by shazron** [comment]
No, everything is just under another org.

Re: the GPL license, no. That is only if you link with the code. ios-deploy is a stand-alone tool. Kinda like gcc (which is gpl), a tool to compile programs that can be of any license.

**Comment by aflofo** [comment]
Okay thanks a lot for the clarifications my man
