### ISSUE TITLE
ios-deploy cannot launch app over wifi

### ISSUE THREAD

**Issue by simongranger** [ios-control/ios-deploy#370]
# Expected behavior
I am trying to use ios-deploy on Apple TV 4K, which doesn't have a usb port.
According to MK.MobileDevice, it supports both USB and WIFI, but it's throwing an error in ios-deploy.
I expect to be able to install and launch my app on Apple TV 4K.

# Actual behavior.
The app doesn't launch and an error is thrown.

The error thrown is:
`Cannot debug a866e6634a2feb235bd1190195a9a8ce18098a33 (J105aAP, J105aAP, uknownos, unkarch) a.k.a. 'core4k' over WIFI.`

I tried skipping that check since it is mentioning uknownos, unkarch.

The second error I then received was:
`	{ "kAMDNoWifiSyncSupportError", "Device doesn't support wireless sync." },`

Could it be that ios-deploy is not using the latest version of MK.MobileDevice?

# Steps to reproduce the problem

$ ios-deploy --justlaunch --bundle /Users/simongranger/git/uswish/allinone/tvos/samples/VideoPlayer/Debug-appletvos/VideoPlayer.app --id a866e6634a2feb235bd1190195a9a8ce18098a33 --noinstall
[....] Waiting for iOS device to be connected
[....] Using a866e6634a2feb235bd1190195a9a8ce18098a33 (J105aAP, J105aAP, uknownos, unkarch) a.k.a. 'core4k'.
------ Debug phase ------
Cannot debug a866e6634a2feb235bd1190195a9a8ce18098a33 (J105aAP, J105aAP, uknownos, unkarch) a.k.a. 'core4k' over WIFI.

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.2 (18C54)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBook Pro (3)
      User Name: Simon Granger (simongranger)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1:53

- [x] 2. ios-deploy -V
1.9.4

- [x] 3. xcodebuild -version
Xcode 10.1
Build version 10B61

- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [x] 6. lldb --version
lldb-1000.11.38.2
  Swift-4.2

**Comment by Volodar** [comment]
I has also the bug

1. sw_vers -productVersion
10.14.4

2. ios-deploy -V
1.9.4

3. xcodebuild -version
Xcode 10.2
Build version 10E125

4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. lldb --version
lldb-1001.0.12.1
  Swift-5.0

7. command line arguments to ios-deploy
./ios-deploy --justlaunch --debug --bundle {path} -i {id-phone}

**Comment by kangwang1988** [comment]
This issue also happens when flutter use ios-deploy to launch ios app.

**Comment by jelecool** [comment]
> This issue also happens when flutter use ios-deploy to launch ios app.
> 
> ```
> void start_remote_debug_server(AMDeviceRef device) {
> 
>     check_error(AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL));
>     assert(gdbfd > 0);
> ```
> 
> will reports error:
> 2019-06-05 17:38:35.123598+0800 ios-deploy[42453:381378] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
> Program ended with exit code: 253

Has Anyone found the way over this error ?

I am running it on an iPhone X with iOS 13 with flutter and VSCode .

**Comment by gabebear** [comment]
I believe this is fixed in the ios-deploy 1.10 beta3 release. You can get it by running
`npm install ios-deploy@beta`

**Comment by jelecool** [comment]
Unable to run it even with this.

I tried running `flutter clean` in my terminal and then rebuild with the new ios-deploy.

My Iphone is running iOS 13 beta and my mac is on Mojave.

**Comment by mayqiyue** [comment]
Unable to run it even with this.
My Iphone is running iOS 13 beta and my mac is on Catalina.

**Comment by he2lec** [comment]
Tried using Xcode 11 with ios-deploy 1.10.0-beta.3 on ios 13.1 beta, same error.

**Comment by iusn** [comment]
Tried using Xcode 11 with ios-deploy 1.10.0-beta.3 on ios 13.1 beta, same error.

**Comment by divan** [comment]
Had the same issue, manually building `ios-deploy` 1.10.0-beta.3 worked for me.
iOS 13, MacOS X 10.4

**Comment by driiftkiing** [comment]
For everyone else, who land here: `Device doesn't support wireless sync.
AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)`

Right now I cant install my app with `ios-deploy` version 1.9.4. (iOS 13, Xcode 11, cordova 9, cordova-ios 5)

But with `ios-deploy` version 1.10.0-beta.3, I can install it ONLY over wifi...

**Comment by ChrisMash** [comment]
Thanks for the tip @driiftkiing!

Is there any word from the iOS-deploy team as to whether non-wifi connections will be possible soon for iOS 13 devices? Or when the stable version will be pushed?

**Comment by fniwes** [comment]
@driiftkiing cordova command fails with the following error:

CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at /Users/fniwes/.nvm/versions/node/v12.11.0/lib/node_modules/cordova/bin/cordova:29:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

I think it is caused because `ios-deploy` reports the version as `1.10.0-beta.3`
How do you solve that issue?

**Comment by driiftkiing** [comment]
one provided solution (workaround): https://github.com/ios-control/ios-deploy/issues/370#issuecomment-534554385
or remove the string `-beta.3` in `src/ios-deploy/version.h` and rebuild it

**Comment by mesqueeb** [comment]
@driiftkiing Two short questions:

❶　How can I:
> remove the string -beta.3 in src/ios-deploy/version.h and rebuild it

When I have it installed via `npm i -g` or via homebrew?

❷　If I try to set everything up via wifi like you said. Will it still be able to use the hot-module reload via the command line when I do `cordova run` ?

**Comment by valjar** [comment]
@mesqueeb for me Wifi options also didn't work, but new beta version 3 did.

How to install.
Install it via `npm i -g`
Open file `src/ios-deploy/version.h` and remove string `-beta.3`
Then run `npm run build` to rebuild it

**Comment by driiftkiing** [comment]
@mesqueeb
> ❶　How can I:
> 
> > remove the string -beta.3 in src/ios-deploy/version.h and rebuild it

1. `npm i -g ios-deploy@beta`
1. Find location of it (`which ios-deploy`) => the result is for me `/usr/local/bin/ios-deploy`
1. Find the real location of the previous result (`python -c 'import os.path; print(os.path.realpath("/usr/local/bin/ios-deploy"))'` or `readlink -f /usr/local/bin/ios-deploy`)
    1. I'm getting `/Users/USER_NAME/.config/yarn/global/node_modules/ios-deploy/build/Release/ios-deploy`
1. Change to the dir: `cd /Users/USER_NAME/.config/yarn/global/node_modules/ios-deploy` (you will not have the same path like me)
1. Open file `src/ios-deploy/version.h` and remove string `-beta.3`
1. Then run `npm run build` to rebuild it

----

Another solution would be to clone this repo, change to the "beta" branch, modify the file, rebuild and replace the existing `ios-deploy` binary.

**Comment by gabebear** [comment]
Closing this since I'll be releasing 1.10.0(no beta) tomorrow.
