### ISSUE TITLE
How to deal with iOS project with apple watch in general?

### ISSUE THREAD

**Issue by gerchicov-bp** [ios-control/ios-deploy#371]
# MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

# Expected behavior
App is launched and works at least

# Actual behavior.
App is launched but crashes on start

# Steps to reproduce the problem
https://habr.com/company/dataart/blog/429196/
ios-deploy --bundle Payload/FoodSniffer.app -W -d

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
```
    System Software Overview:

      System Version: macOS 10.14.1 (18B75)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
...
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7:26
```
- [x] 2. ios-deploy -V
1.9.1
- [x] 3. xcodebuild -version
Xcode 10.1
Build version 10B61
- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version
lldb-1000.11.38.2
  Swift-4.2

**Comment by gabebear** [comment]
ios-deploy will install Apple Watch apps that are packaged inside iOS apps... I haven't looked into the new stand-alone iOS13 apps yet.

There isn't any support for debugging Apple Watch apps yet.

Closing this since it's not very specific about an issue.
