### ISSUE TITLE
How to uninstall this package?

### ISSUE THREAD

**Issue by gerchicov-bp** [ios-control/ios-deploy#374]
Terminal:
```
$ npm uninstall -g ios-deploy
up to date in 0.029s
```
And after it `ios-deploy` still works. How to uninstall it?

**Comment by shazron** [comment]
I just tried it:
```
$ npm uninstall -g ios-deploy
removed 1 package in 0.548s
$ ios-deploy
zsh: command not found: ios-deploy
```

Might be something specific to your configuration. Do a `which ios-deploy` to see where it is installed/linked.

**Comment by totalerex** [comment]
I also can't uninstall it with command provided. 

Same problem as issue reporter mentioned.

**Comment by gabebear** [comment]
Did you install this with npm? If you used `sudo npm` to install it you will need to use `sudo npm` to uninstall it.

On the [README](https://github.com/ios-control/ios-deploy#installation) We now recommend installing ios-deploy via brew and you should be able to uninstall the npm with the following command.

```
sudo npm uninstall -g ios-deploy
```

**Comment by EmiP-EPR** [comment]
npm cache clean --force  
    
npm cache verify
