### ISSUE TITLE
python required

### ISSUE THREAD

**Issue by blondie63** [ios-control/ios-deploy#375]
I've a doubt..
python is required to run ios-deploy ?
if yes, which version ?

**Comment by gabebear** [comment]
LLDB (the debugger) has a built-in Python interpreter used for scripting. https://lldb.llvm.org/use/tutorial.html

I believe this is currently Python2.7, but ios-deploy will need to support whatever is embedded in XCode going forward. Python 2.X will be retired in Jan 2020 and XCode's LLDB will likely move to Python3.X https://stackoverflow.com/questions/4836375/end-of-support-for-python-2-7
