### ISSUE TITLE
ios-deploy --rm  is  fail 

### ISSUE THREAD

**Issue by BraveGang** [ios-control/ios-deploy#386]
Assertion failed: (AFCRemovePath(afc_conn_p, target_filename) == 0), function remove_path, file /usr/local/lib/node_modules/ios-deploy/src/ios-deploy/ios-deploy.m, line 1467.

1.ios-deploy -V  
1.9.4
2. xcodebuild -version
Xcode 10.2.1  Build version 10E1001
3.xcode-select --print-path  
 /Applications/Xcode.app/Contents/Developer
4.gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
5.lldb --version
lldb-1001.0.13.3
  Swift-5.0

**Comment by gabebear** [comment]
closing this for age.

If this is still an issue please reopen and include the command that generated the error
