### ISSUE TITLE
ld: framework not found MobileDevice

### ISSUE THREAD

**Issue by dotconnor** [ios-control/ios-deploy#387]
```
brew install ios-deploy
```
OR
```
yarn global add ios-deploy
```
# Expected behavior
`ios-deploy` should install correctly

# Actual behavior.
Fails with the following error:
```
...
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
# Steps to reproduce the problem
```
brew install ios-deploy
```
# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
```
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A471t)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Mariner
      User Name: Connor Love (connorlove)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 46 minutes
```
- [x] 2. ios-deploy -V
```
zsh: command not found: ios-deploy
```
- [x] 3. xcodebuild -version
```
Xcode 11.0
Build version 11M336w
```
- [x] 4. xcode-select --print-path
```
/Applications/Xcode-beta.app/Contents/Developer
```
- [x] 5. gcc --version
```
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [x] 6. lldb --version
```
lldb-1100.0.25.3
Apple Swift version 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14)
```

**Comment by kangwang1988** [comment]
@dotconnor 
You can edit this Run Script as shown in this picture on 10.15

![image](https://user-images.githubusercontent.com/817851/58948110-fc1e7780-87bb-11e9-8a2c-2f804921fbdf.png)

**Comment by dotconnor** [comment]
@kangwang1988 Thanks!

The script in non-picture format:
```bash
mkdir -p "${PROJECT_DIR}/_Frameworks"
rsync -r /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework "${PROJECT_DIR}/_Frameworks" --exclude=XPCServices --links

```

**Comment by mikehardy** [comment]
Hey, thanks for this project! Just wanted to note for any other intrepid Catalina users out there that after you have the build fail initially on the 1.9.x versions of ios-deploy you may not get it to actually work until you clear out the old partial/failed build like so:

`\rm -fr ~/Library/Developer/Xcode/DerivedData/ios-deploy-*`

After I did that, and an `npm -g uninstall ios-deploy` I was able to install it with `npm -g install ios-deploy@beta` and the compile worked

**Comment by rawbin-** [comment]
@mikehardy works for me too, thanks

**Comment by Edison4mobile** [comment]
Now ios-deploy 1.9.4 is available
I think we don't need to install ios-deploy@beta anymore.
Just npm i ios-deploy -g   is working well.

**Comment by rsmaximiliano** [comment]
Same error "ld: framework not found MobileDevice" with ios-deploy 1.9.4

**Comment by mikehardy** [comment]
@rsmaximiliano please verify you don't have stale build problems: https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142

**Comment by craigstanton** [comment]
> @rsmaximiliano please verify you don't have stale build problems: [#387 (comment)](https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142)

I've done a suggested removal of DerivedData but I still get "ld: framework not found MobileDevice" with ios-deploy 1.9.4

**Comment by mikehardy** [comment]
@Edison4mobile I think your comment is in error - I can reproduce @rsmaximiliano and @craigstanton results, 1.9.4 does not contain the fixes. ios-deploy@beta (currently 1.10.0-beta.3) is what works for me, and if I have attempted 1.9.4 I still have to do my trick of removing the busted build before it installs

`\rm -fr ~/Library/Developer/Xcode/DerivedData/ios-deploy-*`

So I think this is still closed in that there is a fix in master, but it is still unreleased.

**Comment by chrux** [comment]
The beta version worked for me

**Comment by l3ender** [comment]
I'm using 1.9.4 and have cleared my derived data folder and am still seeing the issue. Could we reopen until a new (non-beta) version is released with the fix?

**Comment by chrux** [comment]
What it worked for me was, install the beta and after that uninstall and install the non-beta.

**Comment by mikehardy** [comment]
@chrux that is non-reproducible and you probably have some mixed version that actually got assembled and installed, relying on wierd caching behavior

@l3ender that would be expected. 1.9.4 just won't work, cleared cache or not

Latest 1.10 beta works, after clearing DerivedData, every time

I would also like to see an official release, but since I haven't actually contributed (via a PR or doc update or anything) I feel it's a little presumptious to ask. It's open source :-), it'll be released when it's ready and the maintainer has time. Hopefully soon but the 1.10-beta + clear DerivedData trick works so there's not a blocker for us users

**Comment by chrux** [comment]
@mikehardy Have you tried removing and installing XCode 11.2? I used to have it working until I updated from Xcode 11.1 to Xcode 11.2.

I don't see any presumptions on asking, it's something hasn't been fixed (apparently because it's not released) and it will always depend on the maintiner(s) as they are the only one with access/permissions.

**Comment by mikehardy** [comment]
True enough it depends on the maintainers as they are the only ones that have perms. I have done the install as a test after upgrading to 11.2 I think. I haven't tried it with 11.2.1 though (a fun side fiasco btw - 11.2 cannot be used to create Apple-approved builds at the moment, only 11.2.1 can because of some ugly bug they found, but 11.2.1 is not actually available except as a developer download. Nice work, that). So it all feels a little like a house of cards but I do have it working. I'm in the middle of upgrading my cluster to 11.2.1 and doing a release of my work project so I don't have the ability to say right now whether it's working but I'd be surprised if it isn't

**Comment by l3ender** [comment]
I removed derived data, uninstalled `ios-deploy` (v1.9.4) and am getting an error when trying to install the beta version:

```
-> sudo npm -g install ios-deploy@beta

> ios-deploy@1.10.0-beta.3 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild
...truncated...
2019-11-08 15:31:28.195 xcodebuild[6022:34002] [MT] IDELogStore: Failed to open log store at /var/empty/Library/Developer/Xcode/DerivedData/ios-deploy-fmmaocaaeccvdogvcypgumhupubj/Logs/Build
2019-11-08 15:31:28.195 xcodebuild[6022:34002] [MT] IDELogStore: Failed to open Build log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/var/empty/Library/Developer/Xcode/DerivedData/ios-deploy-fmmaocaaeccvdogvcypgumhupubj/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/var/empty/Library/Developer/Xcode/DerivedData/ios-deploy-fmmaocaaeccvdogvcypgumhupubj/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/var/empty/Library/Developer/Xcode/DerivedData/ios-deploy-fmmaocaaeccvdogvcypgumhupubj/Logs/Build': (513) You don\U2019t have permission to save the file \U201cBuild\U201d in the folder \U201cLogs\U201d.";}.
```

Any thoughts?

**Comment by mikehardy** [comment]
That's really weird @l3ender - looks like some sort of a rabbit-hold of a problem with perms and such. May I ask why you would use 'sudo'? I don't need root perms on my mac to do install global node_modules, those are owned by my user. https://github.com/Carthage/Carthage/issues/2595 is one place I saw that error but I'm not sure how you'd get in that state

**Comment by l3ender** [comment]
@mikehardy I've always had to use `sudo` for global installs, I think because I installed npm using brew. Did you download the zip and reference that in your `PATH`?

**Comment by mikehardy** [comment]
This is pretty off-topic at this point, but brew is also not supposed to be sudo. And npm packages don't need to be. brew actually warns you not to use it as sudo, but that may be what happened?

For what it's worth, I handle all this stuff with a script I call `doctor.sh` in the root of my repo. And the chunk that handles node is like so (using Node Version Manager, a node 10 and a node 12, with global package update and the ios-deploy fix all baked in)

So I never have problems and my colleagues can just "see the doctor" to get updates or whatever, and CI works as well

```bash
# This is the block of versions we try to verify:
NVM_VERSION="0.34.0"
NODE_V10_VERSION="v10.17.0"
NODE_V12_VERSION="v12.13.0"
NVM_INSTALL="false"
AVM_INSTALL="false"

echo "Verifying nvm (Node Version Manager) installation."
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
NVM_LIVE_VERSION=`nvm --version 2>/dev/null`
if [ "$?" != "0" ] || [ "$NVM_LIVE_VERSION" != "$NVM_VERSION" ]; then
  echo "nvm (the Node Version Manager) missing or outdated, installing it."
  echo "##################################################################"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  echo "##################################################################"
  NVM_INSTALL="true"
fi

# Install automatic node version management
echo "Verifying avm (Automatic NVM Management) installation."
if ! [ -e "$HOME/.nvm/auto-nvm.sh" ]; then
  echo "Automatic node.js version switching not enabled, enabling it."
  cp scripts/nvm-auto.sh "$HOME/.nvm/auto-nvm.sh"
  echo ". \$HOME/.nvm/auto-nvm.sh" >> $HOME/.bash_profile
  AVM_INSTALL="true"
fi

echo "Verifying v10 node.js (for firebase functions) is installed."
nvm use $NODE_V10_VERSION >/dev/null 2>&1
if [ "$?" != "0" ]; then
  echo "v10 node.js missing or outdated, installing it."
  nvm install $NODE_V10_VERSION --reinstall-packages-from=v10
  npm -g install yarn@^1.19.1
fi
npm -g update

echo "Verifying current node.js is installed."
nvm use $NODE_V12_VERSION >/dev/null 2>&1
if [ "$?" != "0" ]; then
  echo "Current node.js missing or outdated, installing it."
  nvm install $NODE_V12_VERSION --reinstall-packages-from=node
  npm -g install yarn@^1.19.1
  if [ "$(uname)" == "Darwin" ]; then
    \rm -fr ~/Library/Developer/Xcode/DerivedData/ios-deploy-* && npm -g install ios-deploy@beta
  fi
fi
npm -g update
```

**Comment by x5engine** [comment]
@mikehardy your code is amazing :)
