### ISSUE TITLE
--justlaunch problem

### ISSUE THREAD

**Issue by johanntony** [ios-control/ios-deploy#390]
I use this command "ios-deploy --justlaunch --debug --bundle_id com.xxx.xxx"
but failed with "[ !! ] One of -[b|c|o|l|w|D|R|e|9] is required to proceed!"

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: xxx的MacBook Pro
      User Name: xxx(tony)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 17 minutes

- [ ] 2. ios-deploy -V   
1.9.4
- [ ] 3. xcodebuild -version
Xcode 10.2.1
Build version 10E1001
- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version
lldb-1001.0.13.3
  Swift-5.0

**Comment by pixelomer** [comment]
You didn't specify what to install.

    $ ios-deploy --justlaunch --debug --bundle_id com.xxx.xxx -b /Path/To/Application.app
