### ISSUE TITLE
ios-deploy --download or --upload or --list option does not work with iOS 13 beta

### ISSUE THREAD

**Issue by raltayeche** [ios-control/ios-deploy#392]
Command Used:
ios-deploy -i <DEVICE_UDID> --download --bundle_id <BUNDLE_ID> --to ./local_folder 

# Expected behavior which only occurs on devices running a pre iOS 13 beta iOS version such as iOS 11.x and iOS 12.x
[.....] Waiting for iOS device to be connected
[.....] Using <DEVICE_UDID> (J71bAP, J71bAP, unknownos, unkarch) a.k.a '<DEVICE_NAME>'.
//
/Documents/
/Documents/OutputLog.txt
/Documents/ReturnCode.txt
/Library/
/Library/Caches/
/Library/Preferences/
/SystemData/
/tmp/

ls ./local_folder
Documents      Library       tmp

# Actual behavior on iPhone 6s device running iOS 13 beta. Just outputs two lines below and then exits with return code of 0.
[.....] Waiting for iOS device to be connected
[.....] Using <DEVICE_UDID> (J71bAP, J71bAP, unknownos, unkarch) a.k.a '<DEVICE_NAME>'.

ls ./local_folder

# Steps to reproduce the problem
1) Install iOS 13 beta on a model of iPad or iPhone that supports iOS 13 beta.
2) Launch an App on the iOS 13 beta device using Xcode 11 beta. 
3) Run the previously mentioned  ios-deploy command with the --download option  
4) Check to see if you locally get the folders(Documents,Library,tmp) from the App container
5) Do the same thing using the same version of ios-deploy and Xcode 11 beta on an iOS device running iOS 11 or iOS 12 and you will properly download the folders mentioned in step 4), but not when the device is running iOS 13 beta. 

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
           Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: IMAC
      User Name: userx (userx)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 4 days 2:22

- [ ] 2. ios-deploy -V
          1.9.4
- [ ] 3. xcodebuild -version
          Xcode 11.0
          Build version 11M336w
- [ ] 4. xcode-select --print-path
          /Applications/Xcode-beta.app/Contents/Developer
- [ ] 5. gcc --version
          Apple clang version 11.0.0 (clang-1100.0.20.17)
          Target: x86_64-apple-darwin18.6.0
          Thread model: posix
           InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version
          lldb-1100.0.25.3
          Apple Swift version 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14)

**Comment by Ukalnins** [comment]
@gabebear mentioned that some stuff is fixed on iOS 13 with https://github.com/ios-control/ios-deploy/pull/385 .

**Comment by tiecongli** [comment]
Has it been fixed? I am on 1.9.4 but I have the exact problem

**Comment by hbgogineni** [comment]
I have the same issue on iOS 13.x
Can you please let me know how you installed beta version?
I tried 
npm install ios-deploy@beta
npm install ios-deploy@1.10.0-beta.3
but when I check the version it is showing as 1.9.4

Thanks in advance

**Comment by tiecongli** [comment]
I think you need to put -g in your npm install command

**Comment by gabebear** [comment]
@hbgogineni try installing ios-deploy globally with a `-g` option.
`npm install -g ios-deploy@beta`
Non-global versions are just the node-modules folder. You may also have multiple versions of ios-deploy installed. You can check with `which ios-deploy`.

There is a bug with Catalina and installing via npm which I don't think has been sorted yet... Currently you can work around it by either using `brew` or downloading the source and compiling it yourself with Xcode.

**Comment by hbgogineni** [comment]
Thank you @tiecongli @gabebear 
I did that and It is all good now

**Comment by gabebear** [comment]
1.10.0 is now stable, so this shouldn't be an issue going forward
