### ISSUE TITLE
ios-deploy: Unable to locate DeviceSupport directory on iOS13 beta

### ISSUE THREAD

**Issue by ayechanpyaesonework** [ios-control/ios-deploy#393]
2019-07-03 12:02:54.256 ios-deploy[81527:4091257] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
Could not install build/ios/iphoneos/Runner.app on 0ddb8247417b700e8a3d84655371a8b4602680a7.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

# Expected behavior
Should be able to run on ios 13 beta.

# Actual behavior.
Error launching on device.

# Steps to reproduce the problem
Try to run flutter application from visual studio code.

# System Specs

ios-deploy version 1.9.4

**Comment by Ukalnins** [comment]
What xcode version you have selected with DEVELOPER_DIR or xcode-select ? 

iOS-13 deployments need XCode-11.

**Comment by vadimwe** [comment]
Same for me. Fresh ionic install.

**Comment by gabebear** [comment]
Released 1.10.0 of ios-deploy to stable that should fix this.
