### ISSUE TITLE
--args fails to pass newlines and quotes(") to app

### ISSUE THREAD

**Issue by kikaxa** [ios-control/ios-deploy#395]
Expected:
pass the file as-is as single argument into app:
``ios-deploy -Lmb 1.app -a " \" `cat config.json` \" "``

Actual:
you are required to:
//remove newlines(breaks python), escape quotes with escaped backslashes...
``ios-deploy -Lmb 1.app -a " \" `cat config.json | tr '\n' ' ' | sed 's/\"/\\\\\\\\\"/g' ` \" "``

config.json:
```
{"commands": [  
{"name": "wait_ms", "value":5000},  
{"name": "mock_img", "value":""}  
] }
```

v1.9.4

**Comment by gabebear** [comment]
Closing this in favor of #259
