### ISSUE TITLE
Verify Python version used by ios-deploy matches Python version from lldb

### ISSUE THREAD

**Issue by shazron** [ios-control/ios-deploy#398]
lldb coming with Xcode 11+ may not use system python or a compatible version in the future, as it ships its own python. Apple has said it will remove inclusion of the system python in the future. For reference, macOS Catalina 10.15 still ships with python 2.

See #366

**Comment by gabebear** [comment]
We probably don't care about the paths since they can be any version. We do need the versions of Python to match so we can at least give useful error messages. https://lldb.llvm.org/resources/caveats.html#id2

**Comment by gabebear** [comment]
Closing this for now since it would only break if the version of Python used by the copy of lldb stored at /usr/bin/lldb differed from the version Python in /usr/bin/python, which should not happen.
