### ISSUE TITLE
1.10.0-beta testing thread

### ISSUE THREAD

**Issue by shazron** [ios-control/ios-deploy#399]
Pre-release Release Notes: 
https://github.com/ios-control/ios-deploy/releases/tag/1.10.0-beta.2

Please add your test results or issues to this discussion. 

If you filed a **new issue, paste it here** so I can go and tag the 1.10.0 milestone to it.
Please **refer to the original PR** that the bug originated from if you can (see link in the **Release Notes**).

Install:
`npm install ios-deploy@beta`

**Comment by gabebear** [comment]
Could we get https://github.com/ios-control/ios-deploy/pull/401 into this release?

**Comment by shazron** [comment]
@gabebear don't see why not, it's just a docs change. will get it in

**Comment by shazron** [comment]
If there are no other reports, I'll cut a release on Friday Aug 2nd SGT.

**Comment by shazron** [comment]
#403 added as well

**Comment by gabebear** [comment]
https://github.com/ios-control/ios-deploy/pull/404 is simple, and I think it will help people adopt JSON.

**Comment by shazron** [comment]
#404 added as well
Didn't want to release on a Friday, will do it on my Monday

**Comment by ludufre** [comment]
#405 install failed in Catalina Beta 5

**Comment by gabebear** [comment]
I have a Catalina Mac, but hadn’t tried iOS-deploy on it yet; I will try compiling/running it today.

**Comment by gabebear** [comment]
I don't know what is going on with Catalina failure... The private MobileDevice.framework has moved, but the symlinks should make it work(and it does work on my Catalina MacPro).

I made a bone-headed mistake in #404 for locked devices that #406 fixes.

**Comment by shazron** [comment]
as far as I can tell, Xcode build on Catalina works, I can't get the build to work through npm install though. I remember from previous OS betas sometimes this is quirky, not sure. Maybe I should start publishing on homebrew. 

Pulled in #406

**Comment by gabebear** [comment]
I've mainly been using the version I build, and hadn't realized that `npm install ios-deploy@beta` wasn't installing everything in the 1.10 milestone https://github.com/ios-control/ios-deploy/milestone/14?closed=1.

There are quite a few commits not in the latest beta release(mostly doc changes except the JSON error changes).  https://github.com/ios-control/ios-deploy/compare/1.10.0-beta.2...master

@shazron I have one other minor fix for an issue a co-worker of mine noticed #407. Should a new pre-release get cut before a real release?

**Comment by shazron** [comment]
Pulled in #407. Will deploy a new pre-release

**Comment by shazron** [comment]
Beta 3 pre-release published. See https://github.com/ios-control/ios-deploy/releases/tag/1.10.0-beta.3

**Comment by maryammiahan** [comment]
Thanks for updating I recommend visiting [mobile app development company](http://www.appsquadz.ae/services/iPhone-Development.html) and [iphone app development company](http://www.appsquadz.ae)

**Comment by ChrisMash** [comment]
@shazron As mentioned on #370 it's failing to deploy onto iOS 13 devices over USB (but does work over WiFi)

**Comment by driiftkiing** [comment]
The error messages on the latest and the beta build:

Command: `cordova run ios --device --target TARGET_ID --noprepare --nobuild`

<details>
<summary>
Error message for <code>ios-deploy@1.9.4</code>
</summary>

 ```
------ Debug phase ------
Starting debug of *********-********* (*******, ******, uknownos, unkarch) a.k.a. 'iPhone 11 Pro Max' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
2019-09-25 14:23:59.489 ios-deploy[48623:6596123] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
```
</details>

<details>
<summary>
Error message for <code>ios-deploy@1.10.0-beta.3</code>
</summary>

```
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/Users/user-name/.config/yarn/global/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
</details>

**Comment by B4RteQPl** [comment]
@driiftkiing  I also have this same errors

**Comment by capc0** [comment]
@driiftkiing +1

**Comment by RedMickey** [comment]
@driiftkiing I also faced the same problem

**Comment by ChrisMash** [comment]
@shazron is there any update on whether USB connected iOS 13 devices will be supported again? It's a pretty big issue currently and there doesn't seem to be any activity here anymore :/

**Comment by daviesdoclc** [comment]
Getting exactly the same errors as @driiftkiing.  I installed the beta and now get.
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
App installs, but it doesn't launch it anymore.

**Comment by daviesdoclc** [comment]
I ended up rebuilding the binary with version 1.10.0 and now Cordova can launch it.

**Comment by gabebear** [comment]
@shazron I think 1.10.0 should be good to ship

**Comment by dayaki** [comment]
Thanks, I couldn't install with yarn with previous version, but ``yarn global add ios-deploy@beta`` works flawlessly. Thank you

**Comment by mesqueeb** [comment]
What's the ETA for release of v1.10 ?

**Comment by ambroselittle** [comment]
I used this with success to get around the installer issue on Catalina. 

But it was causing barfing on cordova-ios, which didn't like the beta tag in the version. So I installed [their fix for that prob](https://github.com/apache/cordova-ios/pull/695) from master (`npm i apache/cordova-ios`). That got everything happy. I'm just noting in case others run into that and land here.

Will you update this thread when this goes live in vNext?

**Comment by fxcoudert** [comment]
None of the current versions (stable, beta, master) are building with Xcode 11: https://github.com/ios-control/ios-deploy/issues/422

**Comment by mesqueeb** [comment]
@shazron any progress on your side?

**Comment by gabebear** [comment]
I'm planning on pushing beta4 to stable tomorrow (which should help a lot of people using the package that can't access the beta-labeled-version)

**Comment by gabebear** [comment]
1.10.0 has been set to stable, so closing this thread

**Comment by pajtai** [comment]
when I run `npm install ios-deploy@beta` on Catalina I get:

```bash
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/.../node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)

npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.10.0-beta.3 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR!
npm ERR! Failed at the ios-deploy@1.10.0-beta.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-03-05T22_12_55_254Z-debug.log

```
