### ISSUE TITLE
ios-deploy can not detect my device

### ISSUE THREAD

**Issue by AbdulAli** [ios-control/ios-deploy#402]
My device (Iphone 6s) is connected over the wifi. Xcode can detect it and it is deploying the application as well. But ios-deploy can't detect my device and so i am not being able to deploy my application.

# Actual behavior.
When i run `ios-deploy -c --verbose`
it says: `Best device match: 2` and shows no device.

When i run `instruments -s devices`
it shows my device: GreenMiner (11.3) [782d40dc866a6bebdb9d160c3670f35ca59c9e5f]

# System Specs

1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Abdul’s MacBook Pro
      User Name: Abdul Ali Bangash (abdulalib)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 13 days 9:32
2. ios-deploy -V
1.9.4
3. xcodebuild -version
10.2.1
4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
6. lldb --version
lldb-1001.0.13.3
  Swift-5.0

**Comment by gabebear** [comment]
We've updated a lot of the WiFi detection logic in 1.10.0. Please re-test this and re-open if you are still seeing it.
