### ISSUE TITLE
iOS13: Device doesn't support wireless sync. AMDeviceStartService

### ISSUE THREAD

**Issue by Novan123** [ios-control/ios-deploy#411]
2019-09-26 17:54:05.149 ios-deploy[24720:428783] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Command finished with error code 253: ios-deploy --justlaunch,--no-wifi,-d,-b,/Users/dev/Desktop/Bluebird/platforms/ios/build/device/enaio mobile.app
ios-deploy: Command failed with exit code 253
Error: ios-deploy: Command failed with exit code 253
    at ChildProcess.whenDone (/Users/dev/Desktop/Bluebird/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
error Command failed with exit code 253.

- [ ] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G95)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MACDEVBUILDs Mac mini
      User Name: dev (dev)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 9 days 2:46

- [ ] 2. ios-deploy -V
1.9.4 and also tested with 1.10-beta3 both fail.

- [ ] 3. xcodebuild -version
11.0

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)

**Comment by mcfarljw** [comment]
I'm seeing this too. It deploys to my device but doesn't open it automatically.

**Comment by jimon** [comment]
Same here

**Comment by B4RteQPl** [comment]
same here

**Comment by B4RteQPl** [comment]
any update, how to fix this issue?

**Comment by giladrom** [comment]
same.

**Comment by driiftkiing** [comment]
Check out this [comment](https://github.com/ios-control/ios-deploy/issues/370#issuecomment-534554385), for a workaround.

**Comment by ZhongkaiChen** [comment]
same

**Comment by ylno** [comment]
same

**Comment by piersky** [comment]
Me too

**Comment by giladrom** [comment]
For anyone looking for a quick workaround - what I do in order to use Ionic livereload on iOS is:

`ionic cordova run ios -lc --device --address=0.0.0.0 --no-native-run`

This copies the app into my phone but errors out when trying to run it.

Then, I run 

`ionic cordova run ios -lc --device --address=0.0.0.0` in order to use livereload. This step doesn't actually copy the built app to the phone but it lets me debug it.

**Comment by mesqueeb** [comment]
I  have the same issue, even though I'm trying to just deploy the app through the USB cable...

The other comment says it's fixed in the beta, but I cannot run the beta because it will give me an error that a version number can only have dots and numbers. So there just being the word `"beta"` in the beta, makes it unable for me to cordova run...

**Comment by fastrde** [comment]
### Quick and Dirty Workaround

`npm install -g ios-deploy@beta` (should install version 1.10.0-beta.3)

After installation the new error is 'Version should contain only numbers and dots' 

1. locate the binary (on my mac `/usr/local/lib/node_modules/node/bin/ios-deploy`)
2. use your favorite editor, locate the String`1.10.0-beta.3` in file.
3. Patch it with `1.10.0.1234.3` (SAME LENGTH!, only numbers and dots)

Works again!

**Comment by mesqueeb** [comment]
@fastrde 
Are you sure it's:
- `/usr/local/lib/node_modules/node/bin/ios-deploy` and not 
- `/usr/local/lib/node_modules/ios-deploy` ?

Because the former doesn't exist on my computer, while the latter does. (but then again, what's a computer?)

**Comment by giladrom** [comment]
run ‘which ios-deploy’ and it will show you which one is being executed.

$ which ios-deploy
/Users/giladrom/.nvm/versions/node/v10.9.0/bin/ios-deploy

**Comment by fastrde** [comment]
> @fastrde
> Are you sure it's:
> 
> * `/usr/local/lib/node_modules/node/bin/ios-deploy` and not
> * `/usr/local/lib/node_modules/ios-deploy` ?
> 
> Because the former doesn't exist on my computer, while the latter does. (but then again, what's a computer?)

The location of the binary depends on your installation method (n, nvm, brew, etc.) 

`which ios-deploy` like giladrom said  should give you the correct location

**Comment by RamiAlmofleh** [comment]
> ### Quick and Dirty Workaround
> `npm install -g ios-deploy@beta` (should install version 1.10.0-beta.3)
> 
> After installation the new error is '_Version should contain only numbers and dots_'
> 
> 1. locate the binary (on my mac `/usr/local/lib/node_modules/node/bin/ios-deploy`)
> 2. use your favorite editor to locate the string `1.10.0-beta.3` in file.
> 3. Patch it with `1.10.0.1234.3` (SAME LENGTH!, only numbers and dots)
> 
> Works again!

I am working on cordova project.
i have installed the "1.10.0-beta.3" Version and i can see that in package.json. But when i starting my App i see in log:

```
CordovaError: Promise rejected with non-error: "ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/ios-control/ios-deploy into your path, or do 'npm install -g ios-deploy'"
    at cli.catch.err (/Users/patadams/Development/projekte/camperradar-app/node_modules/cordova/bin/cordova:29:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) 
```

But i have no Idea what you mean with step 2 and step 3?? so i did just step 1

Can you please describe more for 2,3??

**Comment by shiftonetothree** [comment]
> ### Quick and Dirty Workaround
> `npm install -g ios-deploy@beta` (should install version 1.10.0-beta.3)
> 
> After installation the new error is '_Version should contain only numbers and dots_'
> 
> 1. locate the binary (on my mac `/usr/local/lib/node_modules/node/bin/ios-deploy`)
> 2. use your favorite editor to locate the string `1.10.0-beta.3` in file.
> 3. Patch it with `1.10.0.1234.3` (SAME LENGTH!, only numbers and dots)
> 
> Works again!

It's work.
but you need do it with a hex editor like HexFiend.we can't edit with any text editor.

**Comment by fastrde** [comment]
> Can you please describe more for 2,3??

First step is to find the installed ios-deploy version on your disk. `which ios-deploy` does the trick on *nix and mac. 
Second step is to open the file in an editor (not word, something that did not alter the file just by opening it, `vi` is fine und search for the string `1.10.0-beta.3`
Third step: replace this string with `1.10.0.1234.3` but pay attention, that you did not put something other then numbers and dots in the string and don't change the length of the string. It's a binary file, when you change the length, the conditional jumps and address calculation is broken.

**Comment by pipoa** [comment]
> > Can you please describe more for 2,3??
> 
> First step is to find the installed `ios-deploy` version on your disk. `which ios-deploy` does the trick on *nix and mac.
> Second step is to open the file in an editor (not word, something that did not alter the file just by opening it, `vi` is fine) and search for the string `1.10.0-beta.3`

not working for me 
```
2019-11-22 19:51:24.822 ios-deploy[46640:286781] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
[ERROR] An error occurred while running subprocess cordova.
        
        cordova run ios exited with exit code 253.
        
        Re-running this command with the --verbose flag may provide more information.
```

```
mwu-mac:ipifa user$ ios-deploy --version
1.10.0-1234.3

```

**Comment by driiftkiing** [comment]
@pipoa 
> re-check modified version
> 
> ```
> mwu-mac:ipifa user$ ios-deploy --version
> 1.10.0-1234.3
> ```

he said only __numbers and dots__
dash is not allowed

**Comment by j-cimb-barker** [comment]
After I change the version string I get the error:

```
/usr/local/bin/ios-deploy
zsh: operation not permitted: /usr/local/bin/ios-deploy
```

**Comment by pipoa** [comment]
> 
> he said only **numbers and dots**
> dash is not allowed

It's a pity, the same.

ios-deploy checks version string for special characters, if exists it stops running. so we have to remove special characters, but if DASH if allowed, it has nothing to do with  execute result.

**Comment by Gaurvdhenwal** [comment]
getting same error for ionic. How soon can I expect this to be fixed.

**Comment by gabebear** [comment]
1.10.0 is now the stable version, so this should now be resolved.

**Comment by eladnava** [comment]
`npm install -g ios-deploy@1.10.0` fixes it for me 👍
