### ISSUE TITLE
Does ios-deploy support deploying apps with no code signing?

### ISSUE THREAD

**Issue by Wheaties466** [ios-control/ios-deploy#412]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)
I was able to install ios deploy through npm

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

What I am running
sh-3.2# ios-deploy --bundle /var/root/Library/Developer/Xcode/DerivedData/BarMagnet-bfizlgkfunvreqgkoybuczpopyns/Build/Products/Release-iphoneos/BarMagnet.app

It copies everything to the device then throws this

[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 70%] VerifyingApplication
2019-10-15 11:34:02.273 ios-deploy[87448:192175] [ !! ] Error 0xe800801c: No code signature found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

# Expected behavior
I built the app with the CLI flags to not code sign and I know that is working well. But is there a ios-deploy flag I can use to no check for code signing?

# Actual behavior.
it fails to deploy from the code signing error

# Steps to reproduce the problem
download and build BarMagnet without an apple dev account then deploy with ios-deploy

https://github.com/Qata/BarMagnet

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
sh-3.2# system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A582a)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Booted from installation CD/DVD
      Computer Name: iBoss’s MacBook Air
      User Name: System Administrator (root)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3:43

- [ ] 2. ios-deploy -V
ios-deploy -V
1.10.0-beta.3
- [ ] 3. xcodebuild -version
xcodebuild -version
Xcode 11.1
Build version 11A1027
- [ ] 4. xcode-select --print-path
xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
sh-3.2# gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version
lldb --version
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
sh-3.2#

**Comment by gabebear** [comment]
You are trying to install an app that isn't signed... this is definitely not something that is tested.

What is the use-case here?
