### ISSUE TITLE
Neither --args nor --envs are passed to Xamarin.iOS app

### ISSUE THREAD

**Issue by ccxla** [ios-control/ios-deploy#413]
I'm trying to use

```

ios-deploy --debug --args mycoolarg --envs MY_COOL_ENV=1 --bundle my.app

```

where `my.app` is a Xamarin.iOS app, e.g. this [simple app](https://github.com/nunit/nunit.xamarin/tree/master/tests/nunit.runner.tests.iOS). I tried different escape sequences mentioned in other issues (https://github.com/ios-control/ios-deploy/issues/395, https://github.com/ios-control/ios-deploy/issues/250#issuecomment-367099924) to no avail. What am I missing here?

# Expected behavior

The passed values passed via `--args` and `--envs` are accessible in the app via [`Environment.GetCommandLineArgs`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=netframework-4.8) and [`Environment.GetEnvironmentVariables`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariables?view=netframework-4.8), respectively at the [main entry point of the application](https://github.com/nunit/nunit.xamarin/blob/master/tests/nunit.runner.tests.iOS/Main.cs#L33).

# Actual behavior.

None of the values passed via `--envs` and `--args` are accessible. `args` contains exactly one element; the path of the app's working directory.

# Steps to reproduce the problem

1. Build and bundle a Xamarin.iOS app e.g. this [simple app](https://github.com/nunit/nunit.xamarin/tree/master/tests/nunit.runner.tests.iOS) 
2. Execute the command above
3. Print the results of [`Environment.GetCommandLineArgs`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=netframework-4.8) and [`Environment.GetEnvironmentVariables`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariables?view=netframework-4.8) to `Debug`

# System Specs

The connected device is an iPad with iOS 13.1.3.

- [X] 1. system_profiler SPSoftwareDataType
```
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A602)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Disk
      Boot Mode: Normal
      Computer Name:
      User Name:
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 17 minutes
```
- [X] 2. ios-deploy -V
```
1.10.0-beta.3
```
- [X] 3. xcodebuild -version
```
Xcode 11.1
Build version 11A1027
```
- [X] 4. xcode-select --print-path
```
/Applications/Xcode.app/Contents/Developer
```
- [X] 5. gcc --version
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [X] 6. lldb --version
```
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
```

**Comment by gabebear** [comment]
Closing this in favor of #259
