### ISSUE TITLE
npm install of ios-deploy fails with "ld: framework not found MobileDevice" on macOS Catalina

### ISSUE THREAD

**Issue by michelleangela** [ios-control/ios-deploy#415]
# Expected behavior
can install ios-deploy with npm

# Actual behavior
install ios-deploy fails with error
```
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

see attached logs for details
[2019-10-21T21_18_50_387Z-debug.log](https://github.com/ios-control/ios-deploy/files/3752948/2019-10-21T21_18_50_387Z-debug.log)

# Steps to reproduce the problem
Install iso-deploy using npm

```
sudo npm install -g -unsafe-perm=true ios-deploy
```
# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A603)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: macminimdd
      User Name: mdd (mdd)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:07

- [ ] 2. ios-deploy -V
n/a. cannot install ios-deploy

- [x] 3. xcodebuild -version
Xcode 11.1
Build version 11A1027

- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [x] 6. lldb --version
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)

**Comment by michelleangela** [comment]
I tried workarounds posted here https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142 and it didn't work.

**Comment by Kennytian** [comment]
```
1. system_profiler SPSoftwareDataType
Software:
    System Software Overview:

      System Version: macOS 10.15 (19A602)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Kenny’s Mac
      User Name: Kenny (kenny)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 1:31

2. ios-deploy -V
n/a. cannot install ios-deploy

 3. xcodebuild -version
Xcode 11.1
Build version 11A1027

4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. lldb --version
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)

```

The same issue here.

**Comment by Kennytian** [comment]
@michelleangela 

You can try following steps:

1. `npm uninstall -g ios-deploy`

2. `yarn global remove ios-deploy` (if you installed it with yarn global)

3.  `npm i -g ios-deploy@beta`

It's work to me.

**Comment by michelleangela** [comment]
> @michelleangela
> 
> You can try following steps:
> 
> 1. `npm uninstall -g ios-deploy`
> 2. `yarn global remove ios-deploy` (if you installed it with yarn global)
> 3. `npm i -g ios-deploy@beta`
> 
> It's work to me.

The version ios-deploy@beta fails to install as well.

**Comment by matamune94** [comment]
```
** BUILD FAILED **


The following build commands failed:
	Ld /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)
```

not working help

**Comment by lvlkoo** [comment]
Same for me. Any solution for this?

**Comment by michaelpeterlee** [comment]
Re: MacOS 10.15 Catalina

I had the same issue, however it resolved once I `source .bash_profile`. My project bash config file only extended PATH for Android, so can only intuit the terminal session updated it's profile somehow.

HTH

**Comment by michaelpeterlee** [comment]
If anyone is here from the Ionic v1 project, you can ignore this error when building iOS; Just open the project in XCode.

**Comment by michelleangela** [comment]
Other npm packages that take a dependency on the ios-deploy will also fail to install because ios-deploy fails to install. In particular we'd like to get the ios-deploy installation fixed to successfully install the vcremote package.

**Comment by maximovalexei** [comment]
> ```
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Ld /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
> (1 failure)
> ```
> 
> не работает помощь

Аналогичная проблема

**Comment by N-Olbert** [comment]
> Other npm packages that take a dependency on the ios-deploy will also fail to install because ios-deploy fails to install. In particular we'd like to get the ios-deploy installation fixed to successfully install the vcremote package.

Installing ios-deploy via brew works for me on Catalina 10.15.1 (brew uses a precompiled tarball). As vcremote requires/installs brew anyways could it be a workaround to modify the vcremote package to use brew (instead of npm) to install ios-deploy?

**Comment by abowerman** [comment]
> > Other npm packages that take a dependency on the ios-deploy will also fail to install because ios-deploy fails to install. In particular we'd like to get the ios-deploy installation fixed to successfully install the vcremote package.
> 
> @michelleangela Installing ios-deploy via brew works for me on Catalina 10.15 (brew uses a precompiled tarball). As vcremote requires/installs brew anyways could it be a workaround to modify the vcremote package to use brew (instead of npm) to install ios-deploy?

for the people skimming:

`brew install ios-deploy`

Should do the trick.

**Comment by penicsn** [comment]
I solved this way:
- git clone https://github.com/ios-control/ios-deploy.git --branch=1.9.4
- cd to ios-deploy then: npm i
- xcodebuild
- sudo cp -R /[IOS-DEPLOY-DIR] /usr/local/lib/node_modules
- ln -s /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy /usr/local/bin/

**Comment by HristoSmerikarov** [comment]
Had the same issue, but resolved it with a "two-step-before" fix:
https://github.com/flutter/flutter/issues/22595

**Comment by clnorris** [comment]
Do any of the suggested fixes allow vcremote to be installed?  Can vcremote installation be changed to use one of the workarounds?

**Comment by LeoHYS** [comment]
the same issue, and try all the solutions above, still not working.

**Comment by itlijunjie** [comment]
https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142

**Comment by pryorm92** [comment]
> [#387 (comment)](https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142)

Thanks, but that had already been tried by many of us without success.

**Comment by mesqueeb** [comment]
Same issue.

**Comment by mesqueeb** [comment]
I was able to fix this issue by doing what was described [here](https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142):
```
rm -fr ~/Library/Developer/Xcode/DerivedData/ios-deploy-*
npm -g uninstall ios-deploy
npm -g install ios-deploy@beta
```
And it worked.

**Comment by ElieMyIdea** [comment]
> 3\. npm i -g ios-deploy@beta



> > > Other npm packages that take a dependency on the ios-deploy will also fail to install because ios-deploy fails to install. In particular we'd like to get the ios-deploy installation fixed to successfully install the vcremote package.
> > 
> > 
> > @michelleangela Installing ios-deploy via brew works for me on Catalina 10.15 (brew uses a precompiled tarball). As vcremote requires/installs brew anyways could it be a workaround to modify the vcremote package to use brew (instead of npm) to install ios-deploy?
> 
> for the people skimming:
> 
> `brew install ios-deploy`
> 
> Should do the trick.

After correctly cleaning is working well

**Comment by lingzt** [comment]
> @michelleangela
> 
> You can try following steps:
> 
> 1. `npm uninstall -g ios-deploy`
> 2. `yarn global remove ios-deploy` (if you installed it with yarn global)
> 3. `npm i -g ios-deploy@beta`
> 
> It's work to me.

Thanks for the tips. Before all the steps I cleaned my Derivedata, and it works!

**Comment by gabebear** [comment]
I believe this is linked to the version of Xcode used. Here is what testing on my Mojave(10.14.6) Mac shows:
- Xcode 10.2.1 - success
- Xcode 10.3 - success
- Xcode 11.0 - `ld: framework not found MobileDevice`
- Xcode 11.1 - `ld: framework not found MobileDevice`
- Xcode 11.2 - `ld: framework not found MobileDevice`

**Comment by meesha81** [comment]
#install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install ios-deploy, working for Catalina 10.15.1
brew install ios-deploy

**Comment by zakabluk** [comment]
> I believe this is linked to the version of Xcode used. Here is what testing on my Mojave(10.14.6) Mac shows:
> 
> * Xcode 10.2.1 - success
> * Xcode 10.3 - success
> * Xcode 11.0 - `ld: framework not found MobileDevice`
> * Xcode 11.1 - `ld: framework not found MobileDevice`
> * Xcode 11.2 - `ld: framework not found MobileDevice`

@mesqueeb comment helped me at similar situation.

**Comment by gabebear** [comment]
With 1.10.0 released I think this is now resolved.

**Comment by michelleangela** [comment]
> With 1.10.0 released I think this is now resolved.

I tried installing 1.10.0 and still got the error (full log attached):
```
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)
```

Used Xcode 11.2.1

[2019-12-09T22_05_40_717Z-debug.log](https://github.com/ios-control/ios-deploy/files/3941958/2019-12-09T22_05_40_717Z-debug.log)

Is there something I'm missing? A pre-requisite, etc?

**Comment by gabebear** [comment]
@michelleangela Was this on Catalina?

I’m not sure what’s up, but can look at it tomorrow.

To help narrow things down, what is your?
- OS version:
- Xcode version:
- npm version:
- node version:
- bash or zsh:

**Comment by michelleangela** [comment]
The error was on Catalina, which was upgraded from Mojava.

**OS:**

    System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: macminimdd
      User Name: mdd (mdd)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 17 days 4:39

**xcodebuild -version**
Xcode 11.2.1
Build version 11B500

**npm -version**
6.12.0 (I also tried with 6.13.2 and failed)

**node -v**
v12.13.0

**Used bash, upgraded from Mojave**
echo $BASH_VERSION
3.2.57(1)-release

**Comment by gabebear** [comment]
@michelleangela Does installing via `brew` work for you? (e.g. the changes in #429)

I'm going to update a computer to Catalina today to look at this further.

**Comment by gabebear** [comment]
@michelleangela I setup a system extremely close to yours and I'm not seeing a failure.
- macOS 10.15.1 with account updated from Mojave
- `xcodebuild -version` :  Xcode 11.2.1 Build version 11B500
- `npm -version` : 6.12.1
- `node -v` : v12.13.1
- `echo $BASH_VERSION` : 3.2.57(1)-release

My `npm` and `node` versions were .1 higher than the versions than you have(I let brew install the `node@12` package to get those versions).  Can you please try updating to see if the NodeJS maintaners fixed something for Catalina in that release.

The pre-install script that fails is running `./src/scripts/check_reqs.js && xcodebuild`. Can you try running those by themselves and see if either  `./src/scripts/check_reqs.js` fails with something interesting or if `xcodebuild` is what is failing?

**Comment by michelleangela** [comment]
@gabebear 

Quick update:

- Installing ios-deploy via `brew` works. 
- I updated `node` to 13.3.0 via brew and used `npm` 6.13.2, and `sudo npm install -g -unsafe-perm=true ios-deploy` still fails. I also tried clearing the cache of npm.
- The script `./src/scripts/check_reqs.js && xcodebuild` builds successfully from local folder of git cloning of ios-deploy.
- I tried uninstalling `node` and `npm` and then re-installing node.js via downloaded package from https://nodejs.org/ and ios-deploy still fails.

There may be something else configured differently on my machine that's causing the installation to fail.

**Comment by gabebear** [comment]
@michelleangela could you try one more thing?

In a clone of the repo can open package.json and change this line:

- `"preinstall": "./src/scripts/check_reqs.js && xcodebuild",`

to this:

- `"preinstall": "xcodebuild",`

and try running:
```
npm install
```

(also try it with the line unmodified)

The check_reqs.js 'should' only check that you have Xcode installed and fail with a nice message(but it might be failing for some strange reason).

**Comment by michelleangela** [comment]
@gabebear 

`npm install` works for both cases of `preinstall` commands.

One thing I tried was comparing the outputs of building the package under the folder that npm would install ios-deploy with output of installing from npm. When installing via npm, I would use `sudo` and noticed that this would reference a different path for USER_APPS_DIR and USER_LIBRARY_DIR, etc.

Using sudo
```
   export USER_APPS_DIR=/var/root/Applications
   export USER_LIBRARY_DIR=/var/root/Library
```
No sudo
```
   export USER_APPS_DIR=/Users/mdd/Applications
   export USER_LIBRARY_DIR=/Users/mdd/Library
```

Building locally with `sudo`, produces error:
```
npm WARN lifecycle ios-deploy@1.10.0~preinstall: cannot run in wd ios-deploy@1.10.0 ./src/scripts/check_reqs.js && xcodebuild (wd=/usr/local/lib/node_modules/ios-deploy2)
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/ios-deploy2/build/Release/ios-deploy
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy2/build/Release/ios-deploy'
npm ERR! enoent This is related to npm not being able to find a file.
```

Then, I tried installing via npm but without `sudo` this time and installation was successful.

**Comment by gabebear** [comment]
Odd... but glad it's working for you. Hopefully brew installs won't have these weird edge cases.

**Comment by Apuyuseng** [comment]
$ brew install ios-deploy
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/ios-deploy-1.10.0.catalina.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring ios-deploy-1.10.0.catalina.bottle.1.tar.gz
🍺  /usr/local/Cellar/ios-deploy/1.10.0: 5 files, 232.2KB
