### ISSUE TITLE
Installation via yarn?

### ISSUE THREAD

**Issue by dayaki** [ios-control/ios-deploy#416]
Wondering if it's not possible to install ios-deploy via yarn, as I don't use npm anymore? I tried both ``yarn global add ios-deploy --unsafe-perm=true`` and ``yarn global add ios-deploy --allow-root`` but nothing worked. I keep getting ``** BUILD FAILED **``

If possible, what would be the options for installing via yarn?

**Comment by michelleangela** [comment]
@dayaki , can you share which machine and OS version on which installation failed? Is this on macOS Catalina?

**Comment by dayaki** [comment]
Yes, am on macOS Catalina but I was able to install the 1.10.0 beta without any issues.

**Comment by dcalhoun** [comment]
I'm running macOS 10.15.1 and using yarn. I experience the same outcomes. Installing the latest public release fails. Installing `1.10.0-beta.3` succeeded.

**Comment by gabebear** [comment]
I believe this was already working, but with 1.10.0 released this should now be easier.
