### ISSUE TITLE
Cannot cordova run over USB on v1.9.4 && cannot run v1.10-beta

### ISSUE THREAD

**Issue by mesqueeb** [ios-control/ios-deploy#418]
I have this error when cordova is trying to run my app via v1.9.4:
```
[ 95%] Developer disk image mounted successfully
2019-11-06 11:31:32.836 ios-deploy[69011:852596] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
```
This comment asks the author if this will be fixed or not: https://github.com/ios-control/ios-deploy/issues/399#issuecomment-539429184
> @shazron is there any update on whether USB connected iOS 13 devices will be supported again? It's a pretty big issue currently and there doesn't seem to be any activity here anymore :/

But there was no response yet, so I felt this problem deserved its own thread.

Can anyone confirm if this still happens on beta3?
I cannot even run beta3 because of this bug:
```
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/Users/user-name/.config/yarn/global/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Also described in this comment: https://github.com/ios-control/ios-deploy/issues/399#issuecomment-535001966
I have **exactly the same problems** as you @driiftkiing ... I haven't been able to run my apps directly on my phone ever since...

If beta3 could be made just v`1.10` without the "beta" I hope it will run. That is at least IF it also addressed the first issue I mention.

**Comment by gabebear** [comment]
the beta will get re-released as non-beta tomorrow
