### ISSUE TITLE
Status of ios-deploy with Xcode 11

### ISSUE THREAD

**Issue by fxcoudert** [ios-control/ios-deploy#422]
Hi, I'm a Homebrew maintainer, and we're trying to determine how to get ios-deploy to build again with Xcode 11. Right now, I've tried several things:

- latest stable release (1.9.4) does not build because of #415 (`ld: framework not found MobileDevice `)
- latest beta release (1.10.0-beta.3) does not build because:

```
    /bin/sh -c /Users/fx/Library/Developer/Xcode/DerivedData/ios-deploy-dgqwmloyxgwfclggfjcxuaaerflb/Build/Intermediates.noindex/ios-deploy.build/Release/ios-deploy-tests.build/Script-3BF32EF31F5A215300E1699B.sh
rsync: delete_file: rmdir "/tmp/ios-deploy-20191123-72714-yf2pjl/ios-deploy-1.10.0-beta.3/_Frameworks/MobileDevice.framework" failed: Directory not empty (66)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code


Test session results, code coverage, and logs:
	/Users/fx/Library/Developer/Xcode/DerivedData/ios-deploy-dgqwmloyxgwfclggfjcxuaaerflb/Logs/Test/Test-ios-deploy-tests-2019.11.23_14-03-31-+0100.xcresult

Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/fx/Library/Developer/Xcode/DerivedData/ios-deploy-dgqwmloyxgwfclggfjcxuaaerflb/Build/Intermediates.noindex/ios-deploy.build/Release/ios-deploy-tests.build/Script-3BF32EF31F5A215300E1699B.sh
(1 failure)
```

- Current master branch does not build, same error as 1.10.0-beta.3.

Advice is welcome. If ios-deploy is not going to build with Xcode 11 in a reasonable time frame, we may have to remove it from Homebrew.

**Comment by l3ender** [comment]
Did you try the steps described at https://github.com/ios-control/ios-deploy/issues/387#issuecomment-539366142:

> ...after you have the build fail initially on the 1.9.x versions of ios-deploy you may not get it to actually work until you clear out the old partial/failed build like so:
> 
> `\rm -fr ~/Library/Developer/Xcode/DerivedData/ios-deploy-*`
> 
> After I did that, and an `npm -g uninstall ios-deploy` I was able to install it with `npm -g install ios-deploy@beta` and the compile worked

The key is to clear any existing derived data folder and then reinstall using `beta` version. I just did this on Catalina 10.15.1 with Xcode 11.2.1 and it worked.

**Comment by fxcoudert** [comment]
- Homebrew is building in a scratch directory every time (enforced by a sandbox), so there are no leftover files from previous runs anywhere. We do see the errors reported nonetheless.
- If a step is part of the compilation, shouldn't it be included in the build script?

**Comment by fxcoudert** [comment]
@gabebear @shazron I need guidance here, otherwise will recommend removal from Homebrew (and it seems, from comments around, that a lot of users rely on Homebrew as a distribution method for ios-deploy). Thanks!

**Comment by Ukalnins** [comment]
The #387 fixed it for the `ios-deploy` target, but not for the `ios-deploy-tests` target.

**Comment by Ukalnins** [comment]
@fxcoudert  I submitted a PR for the fix. You could verify that it also fixes it for you :-)

**Comment by gabebear** [comment]
I packaged up the most recent changes in a new beta4 release which I'm planning on releasing shortly(early this week) once I do some basic testing.

**Comment by gabebear** [comment]
I've cut 1.10.0 as the stable release(on npmjs.org and github).

@fxcoudert What is the process for updating the brew forumlua? https://formulae.brew.sh/formula/ios-deploy

**Comment by gabebear** [comment]
I believe https://github.com/Homebrew/homebrew-core/pull/47661 will update Homebrew
