### ISSUE TITLE
Licensing re-eval

### ISSUE THREAD

**Issue by gabebear** [ios-control/ios-deploy#431]
The current code base has parts under the GPL and parts under a bespoke 3-part-type license.

1. Cordova/Apache would prefer an APL-compatible license since Cordova is an Apache product. https://github.com/apache/cordova-ios/issues/429.
   - Specifically, the Apache group does not allow licenses that restrict usage in larger works to be imported into Apache. https://www.apache.org/legal/resolved.html#category-x.
2. Moving to GPL-only would **not** help the Apache license, and would also require recreating the file currently under the bespoke license. https://github.com/ios-control/ios-deploy/issues/408

Neither of these need to be addressed immediately(they are both minor), but moving to a single more permissive MIT-type license should be considered for any substantial rework of ios-deploy.

**Comment by brodybits** [comment]
> 1. Cordova/Apache would prefer an APL-compatible license since Cordova is an Apache product.

Agreed, yes.

> [apache/cordova-ios#429](https://github.com/apache/cordova-ios/issues/429)

That would be nice. Unfortunately you can see in apache/cordova-ios#429 that we encountered an issue with loss of functionality. I remain hopeful that someone can get it working 100% with iOS devices (deploy and launch).

> * Specifically, the Apache group does not allow licenses that restrict usage in larger works to be imported into Apache. https://www.apache.org/legal/resolved.html#category-x.

Yes. The workaround has been to keep ios-deploy as a completely separate package, which you can see is maintained outside of the Apache organization. The cordova-ios package simply invokes this tool as an external tool, just like it could invoke Bash as an external tool.

> moving to a single more permissive MIT-type license should be considered for any substantial rework of ios-deploy

I think moving to a more permissive license could only be done be a complete replacement of this ios-deploy tool, like we had discussed in apache/cordova-ios#429 for example.

Considering the statement "Neither of these need to be addressed immediately(they are both minor)", and what seems to be an unknown level of feasibility and required effort, I would favor that we give higher priority to more urgent issues such as getting rid of the UIWebView.

**Comment by gabebear** [comment]
> I think moving to a more permissive license could only be done be a complete replacement of this ios-deploy tool, like we had discussed in apache/cordova-ios#429 for example.

ios-deploy is mostly just a wrapper/interface for the MobileDevice.framework that ships with Xcode.

I realize that we'd have to abandon all the current code... but there isn't actually that much of it. The entire program is basically:
 - 2080 lines in https://github.com/ios-control/ios-deploy/blob/master/src/ios-deploy/ios-deploy.m
 - 177 lines in https://github.com/ios-control/ios-deploy/blob/master/src/scripts/lldb.py

We'd probably want to first create a document describing EXACTLY what ios-deploy does and then re-implement everything from that document... which (to me) seems pretty doable. v2.0 was already slated to rip up ios-deploy into modules rather than the monolith it is now.

**Comment by ptc-shunt** [comment]
If there is a major refactor/reimplementation, it would be great to structure the code so that a python (etc) binding can be put on top cleanly (i.e. not just running an ios-deploy process from inside a python wrapper).

**Comment by gabebear** [comment]
Closing this for now.
