### ISSUE TITLE
Use Meson or CMake for build system

### ISSUE THREAD

**Issue by Ericson2314** [ios-control/ios-deploy#433]
We in https://github.com/NixOS/nixpkgs/ try to build software on Darwin as purely as possible, without XCode and with command line utilities built from source. We also support cross compilation to/from any platform we support building natively. For these reasons it would be nice if ios-deploy didn't have to be built with XCode.

Meson and CMake are both popular, and can generate XCode project files to for the actual building (among a number of options). If ios-deploy were to use a build system like this, distros would benefit by being able to use a non-proprietary build system they can itself build how they please, and developers can still use XCode or whatever they are comfortable with.

If there is interest in this I could contribute the build system rewrite.

**Comment by gabebear** [comment]
ios-deploy requires Apple's MobileDevice.framework library at runtime... so I think ios-deploy doesn't make much sense in a pure Darwin environment(the MobileDevice.framework requirement is not just a compile/link time requirement). 
 https://www.theiphonewiki.com/wiki/MobileDevice_Library#Mac_OS_X:_MobileDevice.framework

libimobiledevice re-implementats Apple's MobileDevice.framework and should be closer to what you are looking for since it works on most OSs. http://www.libimobiledevice.org/

**Comment by Ericson2314** [comment]
I don't think proprietary Apple libraries negate the benefit here. We break up Apple's binaries into many little packages; there's no "100% purity or screw it" dichotomy for us.

See https://github.com/NixOS/nixpkgs/blob/63834d63da872a524af4ee43dd25600ffe69618a/pkgs/development/node-packages/default-v10.nix#L38-L46  for how we package `ios-deploy` today. I would like to just get rid of this `xcodebuild` stuff in there.

**Comment by gabebear** [comment]
> We break up Apple's binaries into many little packages; there's no "100% purity or screw it" dichotomy for us.

MobileDevice.framework only ships with OSX(It’s private and undocumented)... I doubt you are breaking those things up...

ios-deploy’s big touch points with OSX and Xcode:
- Compile Req: Xcode is required either via xcodebuild or via the Xcode UI. (It’s likely a version of cross-compile with clang built from source would work... but why?)
- Linking Req: MovileDevice.framework. The requirement for the presence of this Framework on the system for linking could be removed by generating a TBD file from a valid system... but then we have to regenerate this file to ever use new features/symbols.
- Runtime Req: MovileDevice.framework (only included with OSX, no getting around this).
- Runtime Req: To run/debug apps the user must have a version of Xcode installed that contains a disk image for the correct iOS version of the LLDB debug server. (No getting around this)

It’s possible to install apps to a phone without Xcode, but there wouldn’t be a way to debug or have the app launch after installation(There are much simpler ways to just install apps, so this is something ios-deploy will probably never support).

**Comment by Ericson2314** [comment]
We have other frameworks pulled out, but I didn't yet see `MobileDevice.framework` pulled out, so I'll let this be until it is. Thanks for your replies.
