### ISSUE TITLE
Xcode -> Product -> Analyze: 29 potential memory issues, 1 dead store issue

### ISSUE THREAD

**Issue by shazron** [ios-control/ios-deploy#435]
# Expected behavior

Running Build and Analyze does not result in any issues.

# Actual behavior.

Running Build and Analyze results in 30 issues.

# Steps to reproduce the problem

1. Launch Xcode
2. Load the ios-deploy project
3. Select the ios-deploy target
4. Select Product -> Analyze

# System Specs

Xcode 11.3

**Comment by gabebear** [comment]
Fixed in #436
