### ISSUE TITLE
npm i doesn't work because of  ios-deploy error

### ISSUE THREAD

**Issue by crowolfoxtiger** [ios-control/ios-deploy#449]
Hi,
I can't install npm because of ios-deploy error. 
I already success to install ios-deploy, but npm i doesn't work.
What Should I do?

 **command line arguments** that I used for ios-deploy.
`sudo npm install -g ios-deploy --unsafe-perm=true`

# Expected behavior
install npm

# Actual behavior.
`sudo npm install -g ios-deploy --unsafe-perm=true`
** BUILD SUCCESS **
```
npm i  
** BUILD FAILED **
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.4 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

# Steps to reproduce the problem
1.  
```
     npm uninstall -g ios-deploy
     sudo npm install -g ios-deploy@1.9.4 --unsafe-perm=true
     npm i
```

2.  
    `npm i --unsafe-perm=true`

3.  
```
     turn off SIP
     sudo mv /System/Library/PrivateFrameworks/MobileDevice.framework/XPCServices ~
     sudo npm install -g ios-deploy --unsafe-perm --allow-root
     npm i
```

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

 ☑️  1. system_profiler SPSoftwareDataType
              System Version: macOS 10.15.3 (19D76)
              Kernel Version: Darwin 19.3.0
              Boot Volume: Macintosh HD
              Boot Mode: Normal
 ☑️  2. ios-deploy -V
              1.9.4
 ☑️  3. xcodebuild -version
              Xcode 11.3.1
              Build version 11C504
 ☑️  4. xcode-select --print-path
              /Applications/Xcode.app/Contents/Developer
 ☑️  5. gcc --version
             Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
             Apple clang version 11.0.0 (clang-1100.0.33.17)
             Target: x86_64-apple-darwin19.3.0
             Thread model: posix
              InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ☑️ ] 6. lldb --version
              lldb-1100.0.30.12
              Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)

**Comment by crowolfoxtiger** [comment]
Warnig

```
npm WARN @angular/animations@5.0.0 requires a peer of @angular/core@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/common@5.0.0 requires a peer of @angular/core@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.0.0 requires a peer of @angular/core@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.0.0 requires a peer of @angular/platform-browser@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@5.2.11 requires a peer of @angular/common@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@5.0.0 requires a peer of @angular/core@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@5.0.0 requires a peer of @angular/platform-browser@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@2.4.10 requires a peer of @angular/core@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@2.4.10 requires a peer of @angular/common@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@2.4.10 requires a peer of @angular/compiler@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.4.10 requires a peer of @angular/core@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.4.10 requires a peer of @angular/common@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.4.10 requires a peer of @angular/platform-browser@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/taptic-engine@4.20.0 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/taptic-engine@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/compiler@2.4.10 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/repro@4.20.0 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/repro@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN The package @ionic/app-scripts is included as both a dev and production dependency.
```

**Comment by gabebear** [comment]
Why are you running this?
```
sudo mv /System/Library/PrivateFrameworks/MobileDevice.framework/XPCServices ~
```
I don’t think you would ever want to move anything that is installed as part is OSX out of `/System/Library/`

Can you install other packages with `npm`? (It looks like your npm install is in a bad state?)

**Comment by crowolfoxtiger** [comment]
@gabebear 

I see this page
https://github.com/ios-control/ios-deploy/issues/346

When I add ios platforms, get the same error. So I  have to fix this.

**Comment by crowolfoxtiger** [comment]
Ionic Info

cli packages: (/Users/xxx/.nodenv/versions/8.9.3/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 8.0.0 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.4
    Node       : v8.9.3
    npm        : 6.13.7 
    OS         : macOS
    Xcode      : Xcode 11.3.1 Build version 11C504

**Comment by crowolfoxtiger** [comment]
I resolve this issue !
just replace command
npm i
sudo npm install -g ios-deploy --unsafe-perm=true

**Comment by ralcorta** [comment]
I had an issue similar to that and with it, like @crowolfoxtiger says, I can solve it. 

> sudo npm install -g ios-deploy --unsafe-perm=true

My message was related to a fopen error, trying to open a folder that does not exist. Thanks @crowolfoxtiger !

**Comment by gabebear** [comment]
I highly recommend installing ios-deploy through homebrew. ios-deploy doesn't require root/sudo permissions and generally running npm with `sudo` or using npm to do global installs(`-g`) is not the best way to do things. https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92
