### ISSUE TITLE
The following build commands failed:         Ld /Users/naveensabares/ctp-mobile/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64

### ISSUE THREAD

**Issue by naveensabares92** [ios-control/ios-deploy#450]
**command line arguments** you used for ios-deploy - 

1. **ios-deploy** is a part of **package.json** file in the project.
2. When loading the project in the workspace, "npm install" command runs automatically, invoking the package.json file and attempts to install all the dependencies. 

# Expected behavior
1. "BUILD SUCCEDEED" message should appear
NOTE - Team, I need the ios-deploy to be installed in the node_modules of the project, hence it has to run using the npm install command via terminal in my IDE (Web-storm)

# Actual behavior.
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
        Ld /Users/naveensabares/ctp-mobile/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.3 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/naveensabares/.npm/_logs/2020-02-14T13_20_08_480Z-debug.log

# Steps to reproduce the problem
1. Import project in a workspace and have  "ios-deploy": "1.9.3" configured in package.json 
2. In package-lock.json the below has been configured
 "ios-deploy": 
{
            "version": "1.9.3",
            "resolved": "https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.9.3.tgz",
            "integrity": "sha512-i/8DxXzcL2feqqL6DjUfjqUHyWVmHYNkzZFTyf6yoC4glrI3jQ+8Hhg63vzw/5OoFXN7OyXqjkshAj9c1EsVSw==",
            "dev": true
}
3. When the program runs, ios-deploy is automatically attempted for installation. 
4. I have tried npm install --unsafe-perm --allow-root in the project workspace , same error. 

**I have tried solution provided in [https://github.com/ios-control/ios-deploy/issues/346], But no luck.** 

# System Specs
MAC OS Version - Catalina 10.15.3
node - v10.16.3
npm  - v6.9.0
nvm  -  v0.34.0
Xcode version installed - 11.3.1
**ios-deploy required - 1.9.3**

**Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.**

- [ ] 1. system_profiler SPSoftwareDataType
Software:
    System Software Overview:
      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: NSMacBookPro
      User Name: Naveen B Sabares (naveensabares)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1:02

- [ ] 2. ios-deploy -V
zsh: command not found: ios-deploy
- [ ] 3.xcodebuild -version
Xcode 11.3.1
Build version 11C504

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5.  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-1100.0.30.12
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)

STRUCK IN THIS ISSUE FOR QUITE A WHILE. APPRECIATE ANYONE's HELP ON THIS.

**Comment by gabebear** [comment]
I believe you are seeing what was happening in issue #415 ... which I don't fully understand. It had something to do with permissions when running npm(sudo/non-sudo). Possibly uninstalling anything you've installed globally with the `-g` flag and then try again.

You also probably want to use iosdeploy@v1.10 rather than iosdeploy@v1.9.3. 1.9.3 _should_ have all the _**critical**_ fixes for your setup, but there were a lot of fixes since 1.9.3(e.g. the tests will fail for 1.9.3 on Catalina).

**Comment by gabebear** [comment]
Closing this for now; likely the same as https://github.com/ios-control/ios-deploy/issues/465
