### ISSUE TITLE
spawnSync ios-deploy ENOBUFS

### ISSUE THREAD

**Issue by rafaelmaeuer** [ios-control/ios-deploy#452]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

# Expected behavior
ios-deploy should install the app on the traget device

# Actual behavior.
error Failed to install the app on the device. We've encountered an error in "ios-deploy" command: spawnSync ios-deploy ENOBUFS

# Steps to reproduce the problem
1. Create React Native App (RN 0.61.5)
2. Install VSCode extension for React Native
3. Create new Debug Configuration
```
 {
      "name": "iOS Debug Device",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios",
      "target": "device",
      "scheme": "App Debug",
      "sourceMaps": true
    }
```
4. Install ios-deploy: `brew install ios-deploy`
5. Connect target Device (iPhone 6S)
6. Run Debug Configuration

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [X] 1. system_profiler SPSoftwareDataType
System Version: macOS 10.15.3 (19D76)
Kernel Version: Darwin 19.3.0
Boot Volume: Catalina
Boot Mode: Normal
Secure Virtual Memory: Enabled
System Integrity Protection: Disabled

- [X] 2. ios-deploy -V
1.10.0

- [X] 3. xcodebuild -version
Xcode 11.3.1
Build version 11C504

- [X] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [X] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
      
- [X] 6. lldb --version
lldb-1100.0.30.12
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)

**Comment by rafaelmaeuer** [comment]
It seems to be related to the `Connect via network` option. After disabling installation works again.
![Bildschirmfoto 2020-02-23 um 12 57 58](https://user-images.githubusercontent.com/6418459/75111639-95d4d000-563c-11ea-9d48-07e11fb6eada.png)

**Comment by gabebear** [comment]
Did you also file this against the "VSCode extension for React Native"? I don't know when someone from here would have time to look into this(the problem could be in either the extension or ios-deploy).

**Comment by rafaelmaeuer** [comment]
while creating an issue against the "VSCode extension for React Native" I could't reproduce the issue. Maybe it had to do with two simultaneous connected devices over wifi or one via cable an one with wifi... Actually it works with one device over wifi.

**Comment by rafaelmaeuer** [comment]
Sad it happens again, don't know why

**Comment by gabebear** [comment]
WiFi debugging does mostly work, so closing this for now. WiFi debugging isn't totally stable even in Xcode. Since this involves several different moving parts(VSCode, plugin, ios-deploy, and WiFi debugging) it is a particularly challenging scenario to debug.
