### ISSUE TITLE
Cannot read Info.plist file

### ISSUE THREAD

**Issue by DamonsJ** [ios-control/ios-deploy#458]
when I use ios-deploy ios-deploy --noninteractive --debug --bundle my.ipa
I got the error : 2020-04-16 14:10:18.031 ios-deploy[29262:19920679] [ !! ] Cannot read Info.plist file: file:///Users/sunhonglei/Documents/CITest/CITest/CITest_2020-04-16%2014-10-09/CITest.ipa/Info.plist

why this happen

**Comment by gabebear** [comment]
Sorry for the delay in responding(crazy times),

You will need to extract the files from the .ipa to install the app. The .ipa file is really just a zip file.


```bash
# unzip the IPA file to tmp folder
mkdir ./tmp
cd ./tmp
unzip <path_to_ipa_file>

# run ios-deploy to install the app into iOS device
ios-deploy --noninteractive --debug --bundle  ./Payload/*.app

# clean up the tmp folder
cd ..
rm -r ./tmp
```
