### ISSUE TITLE
--args option undocumented, no example. Fails silently?

### ISSUE THREAD

**Issue by simoncat42** [ios-control/ios-deploy#462]
# Expected behavior

There will be a working example of how to use the --args option in the Readme.md file.

I've tried:
    ios-deploy --debug --envs DYLD_PRINT_STATISTICS=1 --args hello=1 --bundle /Users/chomsky/Desktop/FE22.2.8-apple.app
    ios-deploy --debug --args hello 1 --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "FOO=BAR BAZ=FAZ" --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "-p myarg" --bundle /Users/chomsky/Desktop/webtest.app
    ios-deploy --debug --args "-p FOO=BAR" --bundle /Users/chomsky/Desktop/webtest.app

# Actual behavior.

The app is installed and launched, and I can see the lldb feed, but no launch arguments appear to make it into the app. I don't see any error related to the format of the args option in these calls.

# Steps to reproduce the problem

I've tried running these ios-deploy commands in my terminal.app. 

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType

    System Software Overview:

      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: chomsky
      Boot Mode: Normal
      Computer Name: Simon’s MacBook Pro
      User Name: Simon Braunstein (chomsky)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 19:53

- [ ] 2. ios-deploy -V

1.10.0

- [ ] 3. xcodebuild -version

Xcode 11.5
Build version 11E608c

- [ ] 4. xcode-select --print-path

/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version

lldb-1103.0.22.10
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

**Comment by gabebear** [comment]
This doesn't currently work(see #259)... I don't think there is any technical reason, it just doesn't come up enough and nobody has fixed it. I'll ping someone who may know more on the main bug.

**Comment by gabebear** [comment]
Closing in favor of  #259
