### ISSUE TITLE
npm ERR! Exit status 65

### ISSUE THREAD

**Issue by nipunadh** [ios-control/ios-deploy#466]
** BUILD FAILED **

npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.11.0 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.11.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# Expected behavior

# Actual behavior.
   ** BUILD FAILED **

npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.11.0 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.11.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# Steps to reproduce the problem

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
           System Software Overview:

      System Version: macOS 10.15.6 (19G73)
      Kernel Version: Darwin 19.6.0
      Boot Volume: MacOS
      Boot Mode: Normal
      Computer Name: elmudia one
      User Name: elmudia one (elmudiaone)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 26 minutes

- [ ] 2. ios-deploy -V
      zsh: command not found: ios-deploy

- [ ] 3. xcodebuild -version
       Xcode 11.6
       Build version 11E708

- [ ] 4. xcode-select --print-path
      /Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
        Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
        Apple clang version 11.0.3 (clang-1103.0.32.62)
       Target: x86_64-apple-darwin19.6.0
       Thread model: posix
       InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
       lldb-1103.0.22.10
       Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

**Comment by gabebear** [comment]
What version of node and npm do you have installed? This is definitely something weird with NodeJS. 

This is the same issue as https://github.com/ios-control/ios-deploy/issues/465 which I’ll reopen since this isn’t quite what I originally thought.

**Comment by nipunadh** [comment]
npm -v
6.14.5
node -v
v12.18.2

**Comment by nipunadh** [comment]
sudo npm install -g ios-deploy --unsafe-perm=true

**** BUILD SUCCEEDED ****

**Comment by gabebear** [comment]
What did you change to make it work?

**Comment by nipunadh** [comment]
> What did you change to make it work?
install using this command as you mention to case #465 
sudo npm install -g ios-deploy --unsafe-perm=true
