### ISSUE TITLE
ios-deploy[19597:73082] [ !! ] Bundle id is not specified

### ISSUE THREAD

**Issue by Mosquito19** [ios-control/ios-deploy#468]
1、 I run : $  ios-deploy -B | grep motion,   It can get this :  com.tencent.pitumotiondemo.db; 

2、I run: $ ios-deploy --uninstall_only --bundle_id com.tencent.pitumotiondemo.db ; It can uninstall this app successfully:
[....] Waiting for iOS device to be connected
[....] Using a8d49d0643a5ed24adda414eed68453bea2c1434 (D10AP, iPhone 7, iphoneos, arm64) a.k.a. 'W的 iPhone'.
------ Uninstall phase ------
[ OK ] Uninstalled package with bundle id com.tencent.pitumotiondemo.db

3、 But , when I run : $  ios-deploy --download=/Documents --bundle_id com.tencent.pitumotiondemo.db --to outputVideo
It  dose not works! !!!!!!!
2020-08-13 20:02:50.390 ios-deploy[26114:101969] [ !! ] Unable to find bundle with id: com.tencent.pitumotiondemo.db

HELP!!!!!!!

-----------------This is the system version info -----------------------------------

- [ ] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.4 (19E287)
      Kernel Version: Darwin 19.4.0
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 1:02

- [ ] 2. ios-deploy -V
1.10.0

- [ ] 3. xcodebuild -version
Xcode 11.4
Build version 11E146

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version

onfigured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-1103.0.22.4
Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)

- [ ] **If using NodeJS/npm**
npm@6.14.4 /usr/local/lib/node_modules/npm

  - [ ] 7. npm -v
6.14.4

  - [ ] 8. node -v
v14.0.0

**Comment by Mosquito19** [comment]
Could anyone can tell me how to get the ios app‘s  sandbox file by command line?

**Comment by gabebear** [comment]
Can you list the documents with the following command?
```
ios-deploy -1 com.tencent.pitumotiondemo.db -l/Documents
```

**Comment by Mosquito19** [comment]
> Can you list the documents with the following command?
> 
> ```
> ios-deploy -1 com.tencent.pitumotiondemo.db -l/Documents
> ```
> 
> I haven't played with the download part of ios-deploy in a little while, but I know for sure listing the Documents was working recently.

Thank you very much !  I have find the reasone!  
 Because  the  version of 1.10.0-beta.3  does not work for my system。 1.11.0 version works well !

**Comment by gabebear** [comment]
Glad you got this solved!
