### ISSUE TITLE
Unable to install the patched ipa file into iOS device - AMDeviceSecureInstallApplication (ios_deploy)

### ISSUE THREAD

**Issue by ganesh2183** [ios-control/ios-deploy#477]
Unable to install the patched ipa file into iOS device

OS: MAC Catalina 10.15.5 (installed in VirtualBox)
iOS Device connected : iPhone 11 (Non-Jailbroken Phone)

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType
- [ ] 2. ios-deploy -V : 1.11.2
- [ ] 3. xcodebuild -version: Xcode 11.7, Build version 11E801a
- [ ] 4. xcode-select --print-path: /Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
- [ ] 6. lldb --version: lldb-1103.0.22.10 Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
- [ ] **If using NodeJS/npm**
  - [ ] 7. npm -v: 6.14.6
  - [ ] 8. node -v: v12.18.4

Logged-in using new Apple developer ID in Xcode tool and i have created Apple Development Certificates. 

I created the new project in Xcode, build succeeded and installed successfully into iOS Device. But it fails when i try to install patched ipa to iOS device using ios-deploy tool.

# Steps to reproduce the problem

**ios-deploy --bundle DamnVulnerableIOSApp.app -d -v -W**   
[....] Waiting for iOS device to be connected
Handling device type: 1
Already found device? 0
Hardware Model: N104AP
Device Name: Cloud Keybank iPhone 11 ID:151
Model Name: iPhone 11
SDK Name: iphoneos
Architecture Name: arm64e
Product Version: 13.5.1
Build Version: 17F80
[....] Using 00008030-000E21DA3AF0802E (N104AP, iPhone 11, iphoneos, arm64e) a.k.a. 'Cloud iPhone 11 ID:151'.
------ Install phase ------
[  0%] Found 00008030-000E21DA3AF0802E (N104AP, iPhone 11, iphoneos, arm64e) a.k.a. 'Cloud iPhone 11 ID:151' connected through USB, beginning install
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/META-INF/ to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/_CodeSignature/ to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/_CodeSignature/CodeResources to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/main-bg.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/card-bg.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menuIcon.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/en.lproj/ to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/en.lproj/InfoPlist.strings to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/640_960_SplashScn.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/152x152.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/640x1136_SplashScn.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/120x120.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/AppIcon60x60@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/slider-bg.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/AppIcon40x40@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menuIcon@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/slider-active@2x.png to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/card-bg@2x.png to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/ to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/ to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/g9c-Ju-vFC-view-IFp-rO-8Ad.nib to device
[ 10%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/cLD-LZ-seZ-view-4QP-f7-Xbj.nib to device
[ 10%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/UIViewController-5xJ-MS-CJp.nib to device
...
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Info.plist to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menu-icon@2x.png to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/57x57.png to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/PkgInfo to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2020-09-24 04:06:05.229 **ios-deploy[2865:916828] [ !! ] Error 0xe8008001: An unknown error has occurred. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)**

Not sure the reason for this error from ios_deploy tool.

codesign -v --verbose DamnVulnerableIOSApp.app 
DamnVulnerableIOSApp.app: valid on disk
DamnVulnerableIOSApp.app: satisfies its Designated Requirement

Similarly when check for other patched ipa file,

codesign -v --verbose KMB_QV2.app 
KMB_QV2.app: code object is not signed at all
In architecture: arm64

Need your help to resolve this issue.

**Comment by gabebear** [comment]
Can you install the ipa file via Xcode? You can drag an ipa file to the device in Xcode to install it. https://medium.com/mii-cybersec/another-way-install-ipa-file-537b35d78174

All ios-deploy really does is mimic what Xcode is doing.

**Comment by ganesh2183** [comment]
Yes. i tried to install same ipa file via xcode, it says 'Unable to install xxx.ipa file'.

Actually i m trying to test ios app on Non-Jailbroken iOS device , followed the link- https://github.com/sensepost/objection/wiki/Patching-iOS-Applications

codesign -v --verbose DamnVulnerableIOSApp.app
DamnVulnerableIOSApp.app: valid on disk
DamnVulnerableIOSApp.app: satisfies its Designated Requirement

Similarly when check for other patched ipa file,

codesign -v --verbose KMB_QV2.app
KMB_QV2.app: code object is not signed at all
In architecture: arm64

What could be the reason for this error.

**Comment by gabebear** [comment]
You are having signing issues which is something I am not willing to offer help with.
