### ISSUE TITLE
(Question) How to make the LLDB server listen in all interfaces rather than just localhost?

### ISSUE THREAD

**Issue by felipejfc** [ios-control/ios-deploy#486]
Hi!

I wanted to run ios-deploy into my mac machine and then connect to the LLDB server from another windows machine, for that I need the server to listen into all interfaces rather than just localhost. Is this possible?

Best

**Comment by felipejfc** [comment]
Also is there a way to make debugserver launch the app and wait for connection?

**Comment by gabebear** [comment]
I've never tried connecting from a different computer, but generally that wouldn't be a great idea for most people because of security. Have you tried using SSH to forward the port to the computer you want to use? https://www.ssh.com/ssh/tunneling/example

As far as waiting for a connection; you can set a breakpoint immediately after launching the app with `debugger.GetSelectedTarget().Launch(`  https://github.com/ios-control/ios-deploy/blob/master/src/scripts/lldb.py

**Comment by felipejfc** [comment]
Yeah I got it to work with local port forward! As for my second question, what I mean is to make debugserver launch the app and wait for lldb to connect, it's equivalent as running debugserver with the app we want to debug in the cmd line, like:

debugserver 0.0.0.0:1111 /var/mobile/.../executable

**Comment by gabebear** [comment]
I believe @ivanhernandez13 knows the most about waiting on the debugger scenarios.

**Comment by ivanhernandez13** [comment]
That should be possible, though ios-deploy is not designed for this use case so there are more manual steps involved.

`ios-deploy --bundle $LOCAL_APP_BUNDLE --nolldb`

This should install the local app bundle to the device and print out the port you need to connect to and the path to the remote bundle. e.g. 
```
debugserver port: $PORT
App path: $REMOTE_APP_BUNDLE
```

From lldb you would then do:
```
(lldb) target create $LOCAL_APP_BUNDLE
(lldb) script lldb.debugger.GetSelectedTarget().modules[0].SetPlatformFileSpec(lldb.SBFileSpec($REMOTE_APP_BUNDLE))
(lldb) process connect connect://localhost:$PORT
(lldb) run
```

These btw are just the minimal commands you need to run to get it running. ios-deploy automates running these commands and more [here](https://github.com/ios-control/ios-deploy/blob/master/src/ios-deploy/ios-deploy.m#L32) and [here](https://github.com/ios-control/ios-deploy/blob/master/src/scripts/lldb.py).

We don't start debugserver on the remote device the usual way we would on the command line so unsure how to pass arguments to let debugserver know to start the app and then wait for the connection. Could be as simple as adding an additional argument when the starting the service [here](https://github.com/ios-control/ios-deploy/blob/a4d56c4c85b50ee84a85cc41e96078c76b93b386/src/ios-deploy/ios-deploy.m#L1089) but never looked into it so don't know.

**Comment by felipejfc** [comment]
Yeah, might be, I find this use case very useful for debugging the application using IDA debugger, as for some reason it is unable to launch the process remotely having debug server listening on the device. Only way I got to debug a process with IDA and debugserver was to make the server launch the process so that IDA only attaches to it, that's why I'm asking this.

**Comment by gabebear** [comment]
Closing this for now since I think the bulk has been answered.
