### ISSUE TITLE
Cannot use options that require the debugger against iOS 14.5+ devices

### ISSUE THREAD

**Issue by mylioscottw** [ios-control/ios-deploy#521]
Options such as _--justlaunch_ and _-I_ work fine with devices using iOS 14.4.x and below, but present the following error during the debug phase on 14.5+ devices:

------ Debug phase ------
Starting debug of 00008101-000C0D3E3ED2001E (J307AP, iPad Air 4, iphoneos, arm64e, 14.6, 18F72) a.k.a. 'iPadAir4-Bravo' connected through USB...
[  0%] Looking up developer disk image
[ 90%] Mounting developer disk image
[ 95%] Developer disk image already mounted
Symbol Path: /Users/scottwalker/Library/Developer/Xcode/iOS DeviceSupport/14.6 (18F72)/Symbols
Failed to start debugserver: e8000022 The service is invalid.
Waiting for the device to scan mounted image
**2021-06-14 12:31:01.516 ios-deploy[9284:119043] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, serviceName, NULL, &dbgServiceConnection)**

I have not found anything on the internet about this error, so I don't know if it is specific to what I'm doing. However, it looks like something in these newer iOS versions cause an issue since this worked fine before.

# Expected behavior
Options that use the debugger, like -_-justlaunch_ or _-I_, should work the same on any version of iOS.

# Actual behavior.
Here is the full output or running `ios-deploy -i 00008101-000C0D3E3ED2001E --no-wifi --justlaunch --bundle /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app`:

`[....] Waiting for iOS device to be connected
[....] Using 00008101-000C0D3E3ED2001E (J307AP, iPad Air 4, iphoneos, arm64e, 14.6, 18F72) a.k.a. 'iPadAir4-Bravo'.
------ Install phase ------
[  0%] Found 00008101-000C0D3E3ED2001E (J307AP, iPad Air 4, iphoneos, arm64e, 14.6, 18F72) a.k.a. 'iPadAir4-Bravo' connected through USB, beginning install
[  5%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/META-INF/ to device
[  5%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/icon_calendar_next.png to device
[  5%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/OrientationH@2x.png to device

<Cutting out a bunch of copying messages. I can provide if needed>

[ 49%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/CalendarEventCircle@2x.png to device
[ 49%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/Device-Big-Tablet.png to device
[ 49%] Copying /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app/Search-Rating-Pin-3-On@2x.png to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[100%] Installed package /Users/scottwalker/Downloads/builds/master/daily/7318/iOS/Payload/MyLoApp.app
------ Debug phase ------
Starting debug of 00008101-000C0D3E3ED2001E (J307AP, iPad Air 4, iphoneos, arm64e, 14.6, 18F72) a.k.a. 'iPadAir4-Bravo' connected through USB...
[  0%] Looking up developer disk image
[ 90%] Mounting developer disk image
[ 95%] Developer disk image already mounted
Symbol Path: /Users/scottwalker/Library/Developer/Xcode/iOS DeviceSupport/14.6 (18F72)/Symbols
Failed to start debugserver: e8000022 The service is invalid.
Waiting for the device to scan mounted image
2021-06-14 12:31:01.516 ios-deploy[9284:119043] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, serviceName, NULL, &dbgServiceConnection)`

# Steps to reproduce the problem
1. Connect an iOS device running v14.5 or above.
2. Try running a command that uses the debugger like --justlaunch. You should get the service is invalid error.
3. Repeat with an iOS device running v14.4.x or earlier. There are no issues. 

# System Specs
1. sw_vers -productVersion
11.4

2. ios-deploy -V
1.11.4

3. xcodebuild -version
Xcode 12.3
Build version 12C33

4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. lldb --version
lldb-1200.0.44.2
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)

The ios device I am using is an iPad Air4 with iOS 14.6, but it also happens with iOS 14.5 and on an older iPaidAir2.

**Comment by ivanhernandez13** [comment]
I think you need to upgrade to Xcode 12.5. Xcode 12.3 only includes device support up to iOS 14.3. The debugserver on for iOS 14.3 may be compatible with iOS 14.4 which may explain why you didn't have issues with 14.4.

Alternatively, If a newer Xcode is not an option for some reason you can download only the required files by searching for "ios 14.5 devicesupport" and downloading the zip files for 14.5 and moving the contents into `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/`. If you do not trust those repos then you will need to download 12.5 and extract the 14.5 folder from the DeviceSupport directory and copy it into the same location in your Xcode 12.3.

**Comment by mylioscottw** [comment]
I realized I should have gathered the info from one of the lab machines instead of my laptop. The one I used there did have the newer devicesupport things moved over like you said, but I had the same issue.

Looks like we can use Xcode12.5 on our dev laptops now. Let me upgrade that and try again, making sure the devicesupport stuff is correct. I'll post some updated info soon.

**Comment by mylioscottw** [comment]
Well, it does work fine now on my laptop. I upgraded to Xcode12.5 and also installed 13 Beta along side. I was sure on the lab machines I had upgrade one to XCode12.5 and it didn't work. I also tried copying the ios14.5 items from the path above to a non-Xcode12.5 machine, as well as the 14.5 and 14.6 items from `/Library/Developer/Xcode/iOS DeviceSupport/`, but that also didn't seem to work.

I must have messed up the manual copying process and/or updating Xcode properly. I will try updating those machines properly and see.

Thanks, at least this is info is available now. You can probably close. If the issue comes back, I can reopen.

**Comment by mylioscottw** [comment]
Looks like things work with our lab devices on 14.6. Closing.
