### ISSUE TITLE
Add a method to directly get the device path of the app 

### ISSUE THREAD

**Issue by nisargjhaveri** [ios-control/ios-deploy#524]
It would be useful for external lldb scenarios if we can allow looking up device path of the app given bundle id or the bundle. 

Currently we show the installed path either when running with --nolldb and --bundle, where bundle is now optional. We also show this when we install the app. But there is no way to just get the installed path without either installing or starting the debugserver.

I belive this should be easily possible looking at the code. Suggestions?

**Comment by ivanhernandez13** [comment]
Related comment on a similar issue that goes over how we might do this: https://github.com/ios-control/ios-deploy/issues/475#issuecomment-689572288

**Comment by nisargjhaveri** [comment]
Turns out this is already possible with `ios-deploy --list_bundle_id --json -k 'Path'`. Just that it lists all the apps installed and needs a little parsing to get the path for one specific bundle id.
