### ISSUE TITLE
Usage issue (internal API error)

### ISSUE THREAD

**Issue by HappyStriker** [ios-control/ios-deploy#529]
Hello there,

first of all thank you for maintaining this project. From what it looks like it seems to be great for my planed use case, but unfortunately I am able to use it properly (most likely due to a simple mistake on my end). So please help me with the following situation:

Right now I am trying to deploy a simple SwiftUI based application. For the test case I have created a simple SwiftUI Project called `Pommes` in `~/Desktop/Pommes`. The application itself is just the basic SwiftUI template Xcode sets up when starting a new project. The deployment with Xcode to my iPhone works properly (note: I do not have a paid iOS Developer account, so I am using the 7-day limited experience).

With my currently limited understanding of `ios-deploy` I have tried to install the app with the following commands to my device (connected via usb) using iTerm2:

```
cd ~/Desktop/Pommes
ios-deploy --bundle Pommes --justlaunch
```

This command leads to the following output:

```
[....] Waiting for iOS device to be connected
[....] Using IDOFTHEDEVICEREMOVED (D53pAP, iPhone 12 Pro, iphoneos, arm64e, 14.7.1, 18G82) a.k.a. 'iPhone 12 Pro'.
------ Install phase ------
[  0%] Found IDOFTHEDEVICEREMOVED (D53pAP, iPhone 12 Pro, iphoneos, arm64e, 14.7.1, 18G82) a.k.a. 'iPhone 12 Pro' connected through USB, beginning install
[  5%] Copying /Users/Daniel/Desktop/Pommes/Pommes/META-INF/ to device
[  6%] Copying /Users/Daniel/Desktop/Pommes/Pommes/META-INF/com.apple.ZipMetadata.plist to device
[  9%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/ to device
[ 10%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/AppIcon.appiconset/ to device
[ 12%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/AppIcon.appiconset/Contents.json to device
[ 23%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/AccentColor.colorset/ to device
[ 24%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/AccentColor.colorset/Contents.json to device
[ 26%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Assets.xcassets/Contents.json to device
[ 28%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Preview Content/ to device
[ 30%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Preview Content/Preview Assets.xcassets/ to device
[ 32%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Preview Content/Preview Assets.xcassets/Contents.json to device
[ 34%] Copying /Users/Daniel/Desktop/Pommes/Pommes/PommesApp.swift to device
[ 36%] Copying /Users/Daniel/Desktop/Pommes/Pommes/ContentView.swift to device
[ 40%] Copying /Users/Daniel/Desktop/Pommes/Pommes/Info.plist to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
2021-07-31 09:12:25.181 ios-deploy[29575:1209805] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```

From what I have researched so far I have am guessing on the following points could simply be the issue:

* Do I run `ios-deploy` against the correct directory? Running against the directory `Pommes.xcodeproj` stop earlier at 60% (Error 0xe8000051: Could not inspect the application package), so I guess I am on the right track.
* Some issues in this repository do mention that the app signing needs to take place, as it is not handled by `ios-deploy`. So are there any commands, like `xcodebuild`, to be run before (if so, with which parameters) executing `ios-deploy`?

Thank you very much for your help!

---

`ios-deploy` has been installed using `brew`.

Note: I had installed Xcode 13 beta 2 installed before, but I have removed it from the disc using `AppCleaner` to make sure it is not the issue (as it conflicted with the Xcode command line tools path at first).

```
> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.5.1 (20G80)
      Kernel Version: Darwin 20.6.0
      Boot Volume: Macintosh
      Boot Mode: Normal
      Computer Name: MacBook Pro
      User Name: Firstname Lastname (Daniel)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 2 days 8:18
```

```
> ios-deploy -V
1.11.4
```

```
> xcodebuild -version
Xcode 12.5.1
Build version 12E507
```

```
> xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```

```
> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
> lldb --version
lldb-1205.0.28.2
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
```

```
> npm -v
7.19.1
```

```
> node -v
v16.6.0
```

**Comment by colbyn** [comment]
@HappyStriker Oh just ran into the same problem, and then got it working. It's actually pretty easy, just run `xcodebuild` first with a given output directly, and then tell `ios-deploy` to upload the given bundle to your device.

**Comment by HappyStriker** [comment]
Thanks @colbyn for your answer. That did the trick 👍
