### ISSUE TITLE
Is it possible to run on multiple devices?

### ISSUE THREAD

**Issue by jtothebell** [ios-control/ios-deploy#55]
Hello,

I was wondering if it was possible to simultaneously run apps on mutliple devices using this tool, either attached to the debugger or not. I have some custom automated tests that I would like to kick off on several iPads at once, and it works great on a single device using the following arguments:

`./ios-deploy -i {device id} -b <bundle.app> -d`

or 

`./ios-deploy -i {device id} -b <bundle.app> -d -L`

When I try to do that on multiple devices though (either by calling a script that sets off several ios-deploys in parallel or by manually entering in the commands in to separate prompts, I'm able to deploy to all the devices but only the first device ever starts the app. Is this a known limitation? Or is there any way around it? It looks like I may be able to use ios-deploy to install the app and then Apple's instruments command line interface to launch it with an empty automation script, but I thought I would ask here if there was another way. Ideally I would like to have debug output for every device running, but I would be fine without it as well. 

On a related note, is it possible to start an app that is not built for debugging (ie, one signed with an enterprise adhoc certificate, or one downloaded from the App Store)?

Here is my system information in case it is helpful. Thanks!

sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.4
BuildVersion:   13E28

ios-deploy -V
1.1.0

xcodebuild -version
Xcode 5.1.1
Build version 5B1008

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix

lldb --version
lldb-310.2.37

**Comment by black-square** [comment]
We use the latest version of ios-deploy on 5 devices simultaneously now without any problem. Our command line is:
`ios-deploy --verbose --unbuffered --noninteractive --debug --id ################ --bundle  ipa/Payload/######.app --uninstall`

**Comment by gabebear** [comment]
I'm closing this because it seems not to be an issue anymore(and it's really old)
