### ISSUE TITLE
Error installing IPA: Could not determine bundle id

### ISSUE THREAD

**Issue by zarko-tg** [ios-control/ios-deploy#561]
# Expected behavior

IPA file is installed.

# Actual behavior.

IPA file is NOT installed due to "Could not determine bundle id" error.
The command used to work with ios-deploy ver. 1.11.x. The tool now requires to provide a bundle_id in addition to the bundle (file). When the bundle_id is provided the installation succeeds.

# Steps to reproduce the problem

ios-deploy --bundle app.ipa

# System Specs

System Version: macOS 12.5 (21G72)
Kernel Version: Darwin 21.6.0

ios-deploy: 1.12.0 (installed with brew)
Xcode: 13.4.1
Xcode tools: /Applications/Xcode.app/Contents/Developer

**Comment by joshuaseltzer** [comment]
I've also noticed this "bug" since updating to 1.12.0. As @zarko-tg mentioned, by specifying the actual bundle id with the `-1` flag, it will install successfully.

Was this expected behavior with the latest version?

**Comment by ivanhernandez13** [comment]
Ah this was caused by #503 which assumes we can always extract the bundle id from the given app bundle but that only works for `<name>.app`, not `<name>.ipa`. I'll see about skipping this codepath when installing an ipa

**Comment by ivanhernandez13** [comment]
Fix is committed and included in the latest 1.12.1 release.

**Comment by joshuaseltzer** [comment]
@ivanhernandez13 thanks for the quick fix and release! Just grabbed it and confirmed it's working like before.

Thanks again for maintaining this project!
