### ISSUE TITLE
Latest version on Homebrew

### ISSUE THREAD

**Issue by wusyong** [ios-control/ios-deploy#568]
Sorry to use issue for asking question but there are some issues from new version of Xcode that need commits fixed by latest branch.
Is  there someone still going to maintain the homebrew version?

**Comment by gabebear** [comment]
It's perfectly fine to open an issue for this.

I've meant to clean up a new release for homebrew. I'll try to get either me or @ivanhernandez13 to get a new cut to Homebrew this week.

**Comment by ivanhernandez13** [comment]
@gabebear I'm gonna try to get out a fix for #561 today ([pending commit](https://github.com/ivanhernandez13/ios-deploy/commit/5bb9f2e56301079b9af31bf365f1d49190acbd65)) after which I can also push a new release.

**Comment by ivanhernandez13** [comment]
1.12.1 is now on homebrew: https://github.com/Homebrew/homebrew-core/pull/117678
