### ISSUE TITLE
ios-deploy[62544:3006278] [ !! ] Error 0xe800000e: End of file. AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)

### ISSUE THREAD

**Issue by clod81** [ios-control/ios-deploy#573]
`ios-deploy --bundle App.app/App -W -d`

Note I tried two different apps.
I also tried to reset the trust with all devices and re-trust the device after reconnecting it.
Tried also a different cable to connect the phone to the mac.
I can run apps from Xcode using the same phone/cable/everything.

# Expected behavior
Application being deployed to the device with developer mode enabled.

# Actual behavior.
```
ios-deploy --bundle App.app/App -W -d
[....] Waiting for iOS device to be connected
[....] Using 0000xxxxx (N104AP, iPhone 11, iphoneos, arm64e, 16.3.1, 20D67) a.k.a. 'CLod phone'.
------ Install phase ------
[  0%] Found 0000xxxxx (N104AP, iPhone 11, iphoneos, arm64e, 16.3.1, 20D67) a.k.a. 'CLod phone' connected through USB, beginning install
2023-02-16 12:28:17.349 ios-deploy[62544:3006278] [ !! ] Error 0xe800000e: End of file. AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)
```

# Steps to reproduce the problem
`objection patchipa --source "app.ipa" --codesign-signature 0C8F...`
```
...
Codesigning patched IPA...
```

`ios-deploy --bundle App.app/App -W -d`

Error returned.

# System Specs

```
sw_vers -productVersion
13.2

ios-deploy -V    # installed via brew install ios-deploy and npm module removed (with npm module had the same error - also tried to clone the repo, compile it and use the Release version with same error)
1.12.1

xcodebuild -version
Xcode 14.2

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

lldb --version
lldb-1400.0.38.17
```

**Comment by clod81** [comment]
Never mind, my mistake... sorry

**Comment by relign** [comment]
I found this [issue](https://developer.apple.com/forums/thread/731240?page=2)，This problem exist in iOS 17 and Xcode 15;
I install `.ipa` file  by Xcode;
<img width="1182" alt="image" src="https://github.com/ios-control/ios-deploy/assets/13749042/30999d79-0d50-4389-bd93-ee6fe71ef5f1">
