### ISSUE TITLE
Cant build after uninstalling this package

### ISSUE THREAD

**Issue by itsnyx** [ios-control/ios-deploy#585]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

hello, iI have recently installed this pacakge and the delete it from my macbook,
but now when i do yarn ios or (react-native run-ios)
it shows these logs: 

```
info Found Xcode workspace "myapp.xcworkspace"
info Found booted Myname’s iPhone
error Failed to install the app on the device because we couldn't execute the "ios-deploy" command. Please install it by running "npm install -g ios-deploy" and try again.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

```

My phone is not connected to the mac but in this log it says it found booted device !!

how to fix this issue?
i can build using xcode app to any other emulators.

    "react-native": "0.71.2",
    "ios-deploy": "1.12.2",

i also could not fix it by setting --simulator tag
> npx react-native run-ios --simulator='Iphone 14'
like this dosent work !

**Comment by gabebear** [comment]
This is the ios-deploy project; I think you want to file a bug with react-native. I am not sure what flavor of react-native you are using.

**Comment by itsnyx** [comment]
@gabebear this issue started to happen after installing the ios-deploy on my system and after that when i try to run the project from command line it defaults to my phone which i only connected it once !
