### ISSUE TITLE
A way to launch in suspended state, to run debugger commands before an early crash

### ISSUE THREAD

**Issue by rnikander** [ios-control/ios-deploy#586]
This is more of a feature request than a bug report. If I launch an app like this:

```console
% ios-deploy -b build/Hello.app -d
```

And it crashes right away, I don't have time to setup breakpoints or other things in the debugger. Often when you run something in LLDB you have that chance. Example:

```console
% lldb my_program
(lldb) break set -E c++
(lldb) run    <--- actually starts `my_program`
...
```

Maybe there is a work-around that I don't know about - I'm not very adept with LLDB.

**Comment by back-87** [comment]
you're looking for -n argument, literally read --help.
 
`ios-deploy -n -b "/some/app.app" --debug`
