### ISSUE TITLE
Feature request: ability to detect whether iOS device is locked

### ISSUE THREAD

**Issue by pkisensee** [ios-control/ios-deploy#59]
ios-deploy --detect indicates whether a device is connected, but not if the device is locked.
ios-deploy --debug fails with error 254 if it is unable to launch the app because they device is locked, but it would be nice to be able to detect a locked device in advance of actually deploying.

**Comment by gabebear** [comment]
This is also echoed in the JSON output now.

I'm closing this because it seems not to be an issue anymore(and it's really old)
