### ISSUE TITLE
Add support for IPA files with --uninstall

### ISSUE THREAD

**Issue by JoeFoulkes** [ios-control/ios-deploy#63]
Would it be possible to add support for running ios-deploy --uninstall with a .IPA file?

I'm running this to install an application, with the --uninstall to remove it first...
./ios-deploy --uninstall -b Debug-Release-4.3.ipa

The install works fine, but the uninstall fails with this...

------ Uninstall phase ------
Error: Unable to get bundle id from package Debug-Release-4.3.ipa

The work-around is to extract the IPA file and then run the same command against the extracted .APP folder instead, but it would be good if it worked with IPA off the bat... unless I'm doing something wrong.

Cheers
Joe

**Comment by TFry** [comment]
Bump, this would be a great help with some of nightly automation runs.

**Comment by niravnagda** [comment]
@shazron do you have any idea, when can this be implemented, we really need this functionality

**Comment by ohadschn** [comment]
Until this is implemented, you can use [ipa-deploy](https://github.com/floatinghotpot/ipa-deploy ) as a workaround: `ipa-deploy Debug-Release-4.3.ipa --uninstall`. It works because it basically implements the workaround you mentioned.

**Comment by gabebear** [comment]
closing for age
