### ISSUE TITLE
--uninstall not deleting the application settings?

### ISSUE THREAD

**Issue by JoeFoulkes** [ios-control/ios-deploy#71]
I'm running the following on iOS 8.0.2 and also iOS 8.1...

ios-deploy --uninstall -b path/to/my.app

It's working fine, however the device is somehow retaining application settings.

For example, when I launch my application after a regular/manual installation, it will ask me if I want to allow it access to my location services. If I select "Allow" and then install it again using...

ios-deploy --uninstall -b path/to/my.app

It appears to work in-that the application shortcut will briefly vanish from the springboard (i.e. indicating an uninstall), and then it'll reappear following the successful install. However when I run the application I would expect to see the same location services prompt as before... but I don't see it, and if I look in the device settings I can see that the location permission has been retained from earlier.

I know with iOS 7 the application settings do get reset as part of the --uninstall, so I guess this is something iOS 8 related?

I've also tried another github project which is very similar to yours, it also suffers from the same problem.

**Comment by shazron** [comment]
In iOS 8, user folders are now separate from the app bundle, this is why (most likely in anticipation of a future user profile feature in iOS). ios-deploy probably hasn't taken this into account.

**Comment by shazron** [comment]
Try using the new --uninstall_only option first as a workaround, then deploy the app again.

to debug: use a combination of the new --rm and --list options

**Comment by jamesvanhorn** [comment]
@shazron using --uninstall_only and redeploy did not fix the issue for me. The location permission is retained. Is there any plan to fix this? Interestingly, the push notification permission is correctly deleted on uninstall every time. Any other ideas for a workaround?

**Comment by gabebear** [comment]
Closing for age
