### ISSUE TITLE
detect if an app has been installed

### ISSUE THREAD

**Issue by ghost** [ios-control/ios-deploy#89]
I would love to see a feature where I would be able to see if an app (or bundle identifier) has been installed on a physical device or not

**Comment by dickeylth** [comment]
I know there is another tool that may help you at the moment: https://github.com/imkira/mobiledevice, use `mobiledevice list_installed_apps`

**Comment by shazron** [comment]
There is already code in there to detect an app (or else uninstall could not work). Added as a feature request.

**Comment by gabebear** [comment]
closing for age
