### ISSUE TITLE
ios-deploy should have multi threaded support

### ISSUE THREAD

**Issue by sitay1** [ios-control/ios-deploy#98]
I'm trying to use ios-deploy simulatnesly on two or more devices, and everything goes crap - some of the devices hung.

**Comment by black-square** [comment]
We use the latest version of ios-deploy on 5 devices simultaneously now without any problem. Our command line is:
`ios-deploy --verbose --unbuffered --noninteractive --debug --id ################ --bundle  ipa/Payload/######.app --uninstall`

**Comment by gabebear** [comment]
I'm closing this because it seems not to be an issue anymore(and it's really old)
